# File:		makefile.vc  For stectrl
# Author:	Robin Dunn
# Created:	1-Feb-2000
# Updated:

WXDIR = $(WXWIN)
PROGRAM = resizecd

OBJECTS = $(PROGRAM).obj myframe.obj ownerrnd.obj resizec.obj

!include $(WXDIR)\src\makeprog.vc


