# File:     makefile.g95
# Author:	Robin Dunn
# Created:	1-Feb-2000
# Updated:

WXDIR = $(WXWIN)

TARGET = resizecd
OBJECTS = $(TARGET).o \
	myframe.o \
                ownerrnd.o \
                resizec.o

include $(WXDIR)/src/makeprog.g95


