# Makefile : Builds sample (VC++, WIN32)
# Use FINAL=1 argument to nmake to build final version with no debug info.

# Set WXDIR for your system
WXDIR = $(WXWIN)

PROGRAM=gbtest
OBJECTS = $(PROGRAM).obj 

!include $(WXDIR)\src\makeprog.vc


