wxAdvTable: wxAdvChoicesCellEditor Class Reference
wxAdvChoicesCellEditor Class Reference
Editor for choices data.
#include <wxadvtable.h>
Public Member Functions
wxAdvChoicesCellEditor (wxAdvTable *table, bool editable=false)
Constructs new choices editor.
virtual ~wxAdvChoicesCellEditor ()
virtual bool OneClickActivate ()
Return true, if editor activated with one click (such as boolean cells editor).
Protected Member Functions
virtual void DoActivate ()
virtual void DoDeactivate ()
Detailed Description
Editor for choices data.
Uses wxComboBox for editing.
Constructor & Destructor Documentation
wxAdvChoicesCellEditor::wxAdvChoicesCellEditor (wxAdvTable * table, bool editable = false)
Constructs new choices editor.
Parameters:
table wxAdvTable for which editor to be created
editable true if you want to allow user to edit choice text
References NULL.
wxAdvChoicesCellEditor::~wxAdvChoicesCellEditor () [virtual]
Member Function Documentation
void wxAdvChoicesCellEditor::DoActivate () [protected, virtual]
Implements wxAdvCellEditor.
References wxAdvCellEditor::GetCellRect(), wxAdvCellEditor::GetTable(), wxAdvCellEditor::GetValue(), and wxAdvTableDataModel::StringToChoices().
void wxAdvChoicesCellEditor::DoDeactivate () [protected, virtual]
Implements wxAdvCellEditor.
bool wxAdvChoicesCellEditor::OneClickActivate () [virtual]
Return true, if editor activated with one click (such as boolean cells editor).
Reimplemented from wxAdvCellEditor.
The documentation for this class was generated from the following files:
wxadvtable.h
wxadvtable.cpp