wxAdvTable: wxAdvCoord Class Reference
wxAdvCoord Class Reference
Table cell coordinate.
#include <wxadvtable.h>
Public Member Functions
wxAdvCoord ()
virtual ~wxAdvCoord ()
void Set (size_t row, size_t col)
Sets coordinate.
void operator= (const wxAdvCoord &o)
Sets this coordinate equal to other coordinate.
bool IsSet ()
Checks whether coordinate is set.
void Unset ()
Unset coordinate.
bool Equal (size_t row, size_t col)
Checks coordinate equality.
size_t Row ()
Returns row index.
size_t Col ()
Returns column index.
Detailed Description
Table cell coordinate.
Constructor & Destructor Documentation
wxAdvCoord::wxAdvCoord () [inline]
virtual wxAdvCoord::~wxAdvCoord () [inline, virtual]
Member Function Documentation
size_t wxAdvCoord::Col () [inline]
Returns column index.
Returns:
column index
Referenced by wxAdvCellEditor::GetCellRect(), wxAdvCellEditor::GetCol(), wxAdvCellEditor::GetValue(), wxAdvTable::IsCellHighlighted(), wxAdvTable::SetFocusedBgBrush(), wxAdvTable::SetFocusedPen(), and wxAdvCellEditor::SetNewValue().
bool wxAdvCoord::Equal (size_t row, size_t col) [inline]
Checks coordinate equality.
Parameters:
row row index
col column index
Returns:
true if coordinate equal to row and col parameters
Referenced by wxAdvTable::SetFocusedCell().
bool wxAdvCoord::IsSet () [inline]
Checks whether coordinate is set.
Returns:
true if coordinate is set
References UNDEF_SIZE.
Referenced by wxAdvCellEditor::GetCellRect(), wxAdvCellEditor::GetCol(), wxAdvCellEditor::GetRow(), wxAdvCellEditor::GetValue(), wxAdvTable::SetFocusedBgBrush(), wxAdvTable::SetFocusedPen(), and wxAdvCellEditor::SetNewValue().
void wxAdvCoord::operator= (const wxAdvCoord & o) [inline]
Sets this coordinate equal to other coordinate.
Parameters:
o other coordinate
References m_col, and m_row.
size_t wxAdvCoord::Row () [inline]
Returns row index.
Returns:
row index
Referenced by wxAdvCellEditor::GetCellRect(), wxAdvCellEditor::GetRow(), wxAdvCellEditor::GetValue(), wxAdvTable::IsCellHighlighted(), wxAdvTable::SetFocusedBgBrush(), wxAdvTable::SetFocusedPen(), and wxAdvCellEditor::SetNewValue().
void wxAdvCoord::Set (size_t row, size_t col) [inline]
Sets coordinate.
Parameters:
row row index
col column index
Referenced by wxAdvCellEditor::Activate(), and wxAdvTable::SetFocusedCell().
void wxAdvCoord::Unset () [inline]
Unset coordinate.
References UNDEF_SIZE.
Referenced by wxAdvTable::ClearSelection(), and wxAdvCellEditor::Deactivate().
The documentation for this class was generated from the following file:
wxadvtable.h