wxAdvTable: wxAdvColourCellEditor Class Reference
wxAdvColourCellEditor Class Reference
Editor for color cell values.
#include <wxadvtable.h>
Public Member Functions
wxAdvColourCellEditor (wxAdvTable *table)
virtual ~wxAdvColourCellEditor ()
virtual bool OneClickActivate ()
Return true, if editor activated with one click (such as boolean cells editor).
Protected Member Functions
virtual void DoActivate ()
virtual void DoDeactivate ()
Detailed Description
Editor for color cell values.
Uses wxColourDialog for editing.
Constructor & Destructor Documentation
wxAdvColourCellEditor::wxAdvColourCellEditor (wxAdvTable * table)
wxAdvColourCellEditor::~wxAdvColourCellEditor () [virtual]
Member Function Documentation
void wxAdvColourCellEditor::DoActivate () [protected, virtual]
Implements wxAdvCellEditor.
References wxAdvCellEditor::EndEditing(), wxAdvCellEditor::GetTable(), wxAdvCellEditor::GetValue(), and wxAdvCellEditor::SetNewValue().
void wxAdvColourCellEditor::DoDeactivate () [protected, virtual]
Implements wxAdvCellEditor.
bool wxAdvColourCellEditor::OneClickActivate () [virtual]
Return true, if editor activated with one click (such as boolean cells editor).
Reimplemented from wxAdvCellEditor.
The documentation for this class was generated from the following files:
wxadvtable.h
wxadvtable.cpp