wxAdvTable: wxAdvBoolCellEditor Class Reference
wxAdvBoolCellEditor Class Reference
Editor for boolean cell values.
#include <wxadvtable.h>
Public Member Functions
wxAdvBoolCellEditor (wxAdvTable *table)
virtual ~wxAdvBoolCellEditor ()
virtual bool OneClickActivate ()
Return true, if editor activated with one click (such as boolean cells editor).
Protected Member Functions
virtual void DoActivate ()
virtual void DoDeactivate ()
Detailed Description
Editor for boolean cell values.
Constructor & Destructor Documentation
wxAdvBoolCellEditor::wxAdvBoolCellEditor (wxAdvTable * table)
wxAdvBoolCellEditor::~wxAdvBoolCellEditor () [virtual]
Member Function Documentation
void wxAdvBoolCellEditor::DoActivate () [protected, virtual]
Implements wxAdvCellEditor.
References boolFalse, boolTrue, wxAdvCellEditor::EndEditing(), wxAdvCellEditor::GetValue(), and wxAdvCellEditor::SetNewValue().
void wxAdvBoolCellEditor::DoDeactivate () [protected, virtual]
Implements wxAdvCellEditor.
bool wxAdvBoolCellEditor::OneClickActivate () [virtual]
Return true, if editor activated with one click (such as boolean cells editor).
Reimplemented from wxAdvCellEditor.
The documentation for this class was generated from the following files:
wxadvtable.h
wxadvtable.cpp