wxAdvTable: wxAdvFilterTableDataModel Class Reference
wxAdvFilterTableDataModel Class Reference
Filter table model.
#include <wxadvtable.h>
Public Member Functions
wxAdvFilterTableDataModel (wxAdvTableDataModel *model, size_t numRows, size_t numCols)
Constructs new object.
virtual ~wxAdvFilterTableDataModel ()
virtual wxString GetCellValue (size_t row, size_t col)
Returns cell value in string representation.
virtual bool SetCellValue (size_t row, size_t col, wxString value)
Sets new cell value.
virtual int GetCellFormat (size_t row, size_t col)
Returns cell value format.
virtual bool IsCellEditable (size_t row, size_t col)
Check whether cell is editable.
virtual wxAdvCellAttribute * GetCellAttribute (size_t row, size_t col)
Returns cell attribute.
virtual double GetCellValueAsDouble (size_t row, size_t col)
Returns cell value as double.
virtual wxDateTime GetCellValueAsDateTime (size_t row, size_t col)
Returns cell value as wxDateTime.
virtual void CellChanged (size_t row, size_t col)
Called when single cell value has been changed.
virtual void TableChanged ()
Called when all table data has been changed.
wxAdvTableDataModel * GetUnderlayingModel ()
Returns underlaying table model.
Detailed Description
Filter table model.
Stores data in double array of strings, and updates it when underlaying model data has been changed. This type of model can be used as cache, for example to cache data accessed from database, or another storage with long access time.
Constructor & Destructor Documentation
wxAdvFilterTableDataModel::wxAdvFilterTableDataModel (wxAdvTableDataModel * model, size_t numRows, size_t numCols)
Constructs new object.
Parameters:
model underlaying model, wxAdvFilterTableDataModel takes ownership for _model
numRows number of rows
numCols number of columns
References Observable< O >::AddObserver().
wxAdvFilterTableDataModel::~wxAdvFilterTableDataModel () [virtual]
References Observable< O >::RemoveObserver().
Member Function Documentation
void wxAdvFilterTableDataModel::CellChanged (size_t row, size_t col) [virtual]
Called when single cell value has been changed.
Parameters:
row row index
col column index
Implements wxAdvTableDataModelObserver.
References wxAdvTableDataModel::GetCellValue().
wxAdvCellAttribute * wxAdvFilterTableDataModel::GetCellAttribute (size_t row, size_t col) [virtual]
Returns cell attribute.
Cell attribute is graphical properties such as font, text color, alignment, etc.
Parameters:
row row index
col column index
Returns:
true if cell is editable
Implements wxAdvTableDataModel.
References wxAdvTableDataModel::GetCellAttribute().
int wxAdvFilterTableDataModel::GetCellFormat (size_t row, size_t col) [virtual]
Returns cell value format.
Parameters:
row row index
col column index
Returns:
cell value format
Implements wxAdvTableDataModel.
References wxAdvTableDataModel::GetCellFormat().
Referenced by GetCellValueAsDouble().
wxString wxAdvFilterTableDataModel::GetCellValue (size_t row, size_t col) [virtual]
Returns cell value in string representation.
Parameters:
row row index
col column index
Returns:
cell value
Implements wxAdvTableDataModel.
Referenced by GetCellValueAsDateTime(), and GetCellValueAsDouble().
wxDateTime wxAdvFilterTableDataModel::GetCellValueAsDateTime (size_t row, size_t col) [virtual]
Returns cell value as wxDateTime.
NOTE: not all values can be accessed this way.
Parameters:
row row index
col column index
Returns:
cell value
Reimplemented from wxAdvTableDataModel.
References GetCellValue().
double wxAdvFilterTableDataModel::GetCellValueAsDouble (size_t row, size_t col) [virtual]
Returns cell value as double.
NOTE: not all values can be accessed this way.
Parameters:
row row index
col column index
Returns:
cell value
Reimplemented from wxAdvTableDataModel.
References GetCellFormat(), GetCellValue(), and wxDoubleFormat.
wxAdvTableDataModel * wxAdvFilterTableDataModel::GetUnderlayingModel ()
Returns underlaying table model.
Returns:
underlaying table model
bool wxAdvFilterTableDataModel::IsCellEditable (size_t row, size_t col) [virtual]
Check whether cell is editable.
Parameters:
row row index
col column index
Returns:
true if cell is editable
Implements wxAdvTableDataModel.
References wxAdvTableDataModel::IsCellEditable().
bool wxAdvFilterTableDataModel::SetCellValue (size_t row, size_t col, wxString value) [virtual]
Sets new cell value.
Parameters:
row row index
col column index
cell value in string representation
Returns:
true if cell value is set
Implements wxAdvTableDataModel.
References wxAdvTableDataModel::SetCellValue().
void wxAdvFilterTableDataModel::TableChanged () [virtual]
Called when all table data has been changed.
Implements wxAdvTableDataModelObserver.
The documentation for this class was generated from the following files:
wxadvtable.h
wxadvtable.cpp