wxAdvTable: wxAdvTableDataModel Class Reference
wxAdvTableDataModel Class Reference
Model for wxAdvTable data, such as cell values, formats.
#include <wxadvtable.h>
Public Member Functions
wxAdvTableDataModel ()
virtual ~wxAdvTableDataModel ()
virtual wxString GetCellValue (size_t row, size_t col)=0
Returns cell value in string representation.
virtual bool SetCellValue (size_t row, size_t col, wxString value)=0
Sets new cell value.
virtual int GetCellFormat (size_t row, size_t col)=0
Returns cell value format.
virtual bool IsCellEditable (size_t row, size_t col)=0
Check whether cell is editable.
virtual wxAdvCellAttribute * GetCellAttribute (size_t row, size_t col)=0
Returns cell attribute.
virtual double GetCellValueAsDouble (size_t row, size_t col)
Returns cell value as double.
virtual wxDateTime GetCellValueAsDateTime (size_t row, size_t col)
Returns cell value as wxDateTime.
Static Public Member Functions
static void StringToChoices (const wxString &value, wxString &selection, wxArrayString &choices)
Parse choices string representation, and split it to choices elements.
static wxString ChoicesToString (const wxString &selection, wxArrayString &choices)
Encode choices to string representation.
static wxString ChoicesSelection (const wxString &value)
Returns current selected choice.
Protected Member Functions
FIRE_WITH_VALUE2 (CellChanged, size_t, row, size_t, col)
FIRE_VOID (TableChanged)
Detailed Description
Model for wxAdvTable data, such as cell values, formats.
Constructor & Destructor Documentation
wxAdvTableDataModel::wxAdvTableDataModel ()
wxAdvTableDataModel::~wxAdvTableDataModel () [virtual]
Member Function Documentation
wxString wxAdvTableDataModel::ChoicesSelection (const wxString & value) [static]
Returns current selected choice.
Parameters:
value choices string representation
Returns:
current selected choice
Referenced by wxAdvChoicesCellRenderer::Draw().
wxString wxAdvTableDataModel::ChoicesToString (const wxString & selection, wxArrayString & choices) [static]
Encode choices to string representation.
Parameters:
selection current selected choice
choices choices elements
Returns:
choices string representation
wxAdvTableDataModel::FIRE_VOID (TableChanged) [protected]
wxAdvTableDataModel::FIRE_WITH_VALUE2 (CellChanged , size_t , row , size_t , col) [protected]
virtual wxAdvCellAttribute* wxAdvTableDataModel::GetCellAttribute (size_t row, size_t col) [pure virtual]
Returns cell attribute.
Cell attribute is graphical properties such as font, text color, alignment, etc.
Parameters:
row row index
col column index
Returns:
true if cell is editable
Implemented in wxAdvDefaultTableDataModel, and wxAdvFilterTableDataModel.
Referenced by wxAdvFilterTableDataModel::GetCellAttribute().
virtual int wxAdvTableDataModel::GetCellFormat (size_t row, size_t col) [pure virtual]
Returns cell value format.
Parameters:
row row index
col column index
Returns:
cell value format
Implemented in wxAdvDefaultTableDataModel, and wxAdvFilterTableDataModel.
Referenced by wxAdvTableDateTimeSorter::Compare(), wxAdvTableDoubleSorter::Compare(), wxAdvFilterTableDataModel::GetCellFormat(), wxAdvTable::GetEditorForCell(), and wxAdvTable::GetRendererForCell().
virtual wxString wxAdvTableDataModel::GetCellValue (size_t row, size_t col) [pure virtual]
Returns cell value in string representation.
Parameters:
row row index
col column index
Returns:
cell value
Implemented in wxAdvDefaultTableDataModel, and wxAdvFilterTableDataModel.
Referenced by wxAdvFilterTableDataModel::CellChanged(), wxAdvTableStringSorter::Compare(), and wxAdvTable::GetCellValue().
virtual wxDateTime wxAdvTableDataModel::GetCellValueAsDateTime (size_t row, size_t col) [virtual]
Returns cell value as wxDateTime.
NOTE: not all values can be accessed this way.
Parameters:
row row index
col column index
Returns:
cell value
Reimplemented in wxAdvDefaultTableDataModel, and wxAdvFilterTableDataModel.
Referenced by wxAdvTableDateTimeSorter::Compare().
virtual double wxAdvTableDataModel::GetCellValueAsDouble (size_t row, size_t col) [virtual]
Returns cell value as double.
NOTE: not all values can be accessed this way.
Parameters:
row row index
col column index
Returns:
cell value
Reimplemented in wxAdvDefaultTableDataModel, and wxAdvFilterTableDataModel.
Referenced by wxAdvTableDoubleSorter::Compare().
virtual bool wxAdvTableDataModel::IsCellEditable (size_t row, size_t col) [pure virtual]
Check whether cell is editable.
Parameters:
row row index
col column index
Returns:
true if cell is editable
Implemented in wxAdvDefaultTableDataModel, and wxAdvFilterTableDataModel.
Referenced by wxAdvTable::IsCellEditable(), and wxAdvFilterTableDataModel::IsCellEditable().
virtual bool wxAdvTableDataModel::SetCellValue (size_t row, size_t col, wxString value) [pure virtual]
Sets new cell value.
Parameters:
row row index
col column index
cell value in string representation
Returns:
true if cell value is set
Implemented in wxAdvDefaultTableDataModel, and wxAdvFilterTableDataModel.
Referenced by wxAdvTable::ChangeCellValue(), and wxAdvFilterTableDataModel::SetCellValue().
void wxAdvTableDataModel::StringToChoices (const wxString & value, wxString & selection, wxArrayString & choices) [static]
Parse choices string representation, and split it to choices elements.
Parameters:
value choices string representation
selection output for current selected choice
choices output for choices elements
Referenced by wxAdvChoicesCellEditor::DoActivate().
The documentation for this class was generated from the following files:
wxadvtable.h
wxadvtable.cpp