wxAdvTable: wxAdvHdrCell Class Reference
wxAdvHdrCell Class Reference
Row/column description.
#include <wxadvtable.h>
Public Member Functions
wxAdvHdrCell (const wxAdvHdrCell &o)
Copy constructor.
wxAdvHdrCell (const wxChar *label=wxT(""))
Construct new header cell.
wxAdvHdrCell (const wxString &label)
Construct new header cell.
virtual ~wxAdvHdrCell ()
wxAdvHdrCell & Sub (wxAdvHdrCell subHdrCell)
Adds sub row/column.
wxAdvHdrCell & Sub (const wxChar *label)
Adds sub row/column.
bool IsComposite ()
Check if cell is composite.
wxAdvHdrCell & AlignVertical (int alignVertical)
Sets vertical text alignment for header cell.
int AlignVertical ()
Returns vertical text alignment.
wxAdvHdrCell & AlignHorizontal (int alignHorizontal)
Sets horizontal text alignment for header cell.
int AlignHorizontal ()
Returns horizontal text alignment.
wxAdvHdrCell & SetVerticalText (bool verticalText)
Set whether to vertical text label.
wxAdvHdrCell & VerticalText ()
Marks cell to draw label vertical.
bool IsVerticalText ()
Checks whether label text is vertical.
wxAdvHdrCell & SetSortable (bool sortable)
Marks cell as sortable or not.
wxAdvHdrCell & Sortable ()
Marks cell as sortable.
bool IsSortable ()
Checks whether cell is sortable.
wxAdvHdrCell & ResizeAllowed ()
Allow row/column resize by mouse.
wxAdvHdrCell & Renderer (wxAdvHdrCellRenderer *renderer)
Sets renderer to draw cell content.
wxAdvHdrCellRenderer * Renderer ()
Returns renderer to draw cell content.
wxAdvHdrCell & Spacing (wxCoord spacing)
Sets distance between edges and cell content.
wxCoord Spacing ()
Returns spacing - distance between edges and cell content.
wxAdvHdrCell & Label (const wxString &label)
Set header cell label.
const wxString & Label ()
Returns header cell label.
wxAdvHdrCell & Size (wxCoord size)
Sets size (width for column, height for row) for header cell.
wxCoord Size ()
Returns size.
wxAdvHdrCell & MinSize (wxCoord minSize)
Sets minimal size (width for column, height for row) for header cell.
wxCoord MinSize ()
Returns minimal size.
wxAdvHdrCell & MaxSize (wxCoord maxSize)
Sets maximal size (width for column, height for row) for header cell.
wxCoord MaxSize ()
Returns maximal size.
bool IsSubcell ()
Checks whether cell is sub cell of another cell.
size_t GetSubCellCount ()
Returns subcell count.
wxAdvHdrCell * GetSubCell (size_t index)
Returns subcell at index.
wxSize CalcExtent (wxDC &dc)
Returns size, needed for cell.
size_t Layers ()
Returns maximal sublayer count.
size_t GetDecompCellCount ()
Returns hdrCell layer header cell count.
bool IsRow ()
Returns true, if hdrCell is row, false - if column.
size_t Index ()
Returns decomposed index.
bool IsRightEdge ()
wxAdvHdrCell * RightSibling ()
Static Public Member Functions
static size_t GetDecompCellCount (wxAdvHdrCell *cells, size_t numCells)
Returns summary hdrCell layer cell count.
Static Public Attributes
static const int defaultSpacing = 5
static const int defaultAlignVertical = wxALIGN_CENTER_VERTICAL
static const int defaultAlignHorizontal = wxALIGN_CENTER_HORIZONTAL
Friends
class wxAdvTable
class wxAdvDefaultHdrCellRenderer
Detailed Description
Row/column description.
Contains attributes to draw and arrange header cell, such as:
cell label
size (if not set it will be calculated automatically)
label horizontal/vertical alignment
spacing - distance between label and cell edges
sortable or not
horizontal or vertical label text
Header cell can be simple or composite. Composite cells contains one or more subcells.
Constructor & Destructor Documentation
wxAdvHdrCell::wxAdvHdrCell (const wxAdvHdrCell & o) [inline]
Copy constructor.
References wxAdvHdrCellRenderer::Clone(), m_alignHorizontal, m_alignVertical, m_decompIndex, m_isRow, m_label, m_maxSize, m_minSize, m_parent, m_rc, m_renderer, m_resizeAllowed, m_size, m_sortable, m_spacing, m_subCells, m_subIndex, m_table, m_verticalText, and NULL.
wxAdvHdrCell::wxAdvHdrCell (const wxChar * label = wxT("")) [inline]
Construct new header cell.
Parameters:
label header cell label
wxAdvHdrCell::wxAdvHdrCell (const wxString & label) [inline]
Construct new header cell.
Parameters:
label header cell label
virtual wxAdvHdrCell::~wxAdvHdrCell () [inline, virtual]
Member Function Documentation
int wxAdvHdrCell::AlignHorizontal () [inline]
Returns horizontal text alignment.
Returns:
horizontal text alignment
wxAdvHdrCell& wxAdvHdrCell::AlignHorizontal (int alignHorizontal) [inline]
Sets horizontal text alignment for header cell.
Parameters:
alignHorizontal horizontal alignment, possible values are: wxALIGN_LEFT, wxALIGN_CENTER_HORIZONTAL, wxALIGN_RIGHT
Returns:
reference to itself
int wxAdvHdrCell::AlignVertical () [inline]
Returns vertical text alignment.
Returns:
vertical text alignment
wxAdvHdrCell& wxAdvHdrCell::AlignVertical (int alignVertical) [inline]
Sets vertical text alignment for header cell.
Parameters:
alignVertical vertical alignment, possible values are: wxALIGN_TOP, wxALIGN_CENTER_VERTICAL, wxALIGN_BOTTOM
Returns:
reference to itself
wxSize wxAdvHdrCell::CalcExtent (wxDC & dc) [inline]
Returns size, needed for cell.
Parameters:
dc device context
size_t wxAdvHdrCell::GetDecompCellCount (wxAdvHdrCell * cells, size_t numCells) [static]
Returns summary hdrCell layer cell count.
Parameters:
cells hdrCell array
numCells number of elements in cells array
Returns:
summary hdrCell layer cell count
References GetDecompCellCount().
size_t wxAdvHdrCell::GetDecompCellCount () [inline]
Returns hdrCell layer header cell count.
e.g. real row/column count.
Returns:
References FOREACH_HDRCELL.
Referenced by GetDecompCellCount().
wxAdvHdrCell* wxAdvHdrCell::GetSubCell (size_t index) [inline]
Returns subcell at index.
Parameters:
index subcell index
Returns:
subcell
size_t wxAdvHdrCell::GetSubCellCount () [inline]
Returns subcell count.
Returns:
subcell count
size_t wxAdvHdrCell::Index () [inline]
Returns decomposed index.
If hdrCell is composite, it will return UNDEF_SIZE.
Returns:
decomposed index
bool wxAdvHdrCell::IsComposite () [inline]
Check if cell is composite.
Composite cell contains one or more subcells.
Returns:
true if cell is composite
Referenced by wxAdvTable::CanSortByHdrCell().
bool wxAdvHdrCell::IsRightEdge () [inline]
References NULL.
bool wxAdvHdrCell::IsRow () [inline]
Returns true, if hdrCell is row, false - if column.
Returns:
true if this hdrCell is row
bool wxAdvHdrCell::IsSortable () [inline]
Checks whether cell is sortable.
Returns:
true cell is sortable
Referenced by wxAdvTable::CanSortByHdrCell().
bool wxAdvHdrCell::IsSubcell () [inline]
Checks whether cell is sub cell of another cell.
Returns:
true if this cell is sub cell of another cell
References NULL.
bool wxAdvHdrCell::IsVerticalText () [inline]
Checks whether label text is vertical.
Returns:
true if label text is vertical
const wxString& wxAdvHdrCell::Label () [inline]
Returns header cell label.
Returns:
label
wxAdvHdrCell& wxAdvHdrCell::Label (const wxString & label) [inline]
Set header cell label.
Parameters:
label label
Returns:
reference to itself
Referenced by wxAdvTable::Create(), and wxAdvTable::DestroyTable().
size_t wxAdvHdrCell::Layers () [inline]
Returns maximal sublayer count.
1 - for not composite header cell.
Returns:
sublayer count
References FOREACH_HDRCELL.
wxCoord wxAdvHdrCell::MaxSize () [inline]
Returns maximal size.
Returns:
maximal size
wxAdvHdrCell& wxAdvHdrCell::MaxSize (wxCoord maxSize) [inline]
Sets maximal size (width for column, height for row) for header cell.
Parameters:
maxSize new maximal size
Returns:
reference to itself
wxCoord wxAdvHdrCell::MinSize () [inline]
Returns minimal size.
Returns:
minimal size
wxAdvHdrCell& wxAdvHdrCell::MinSize (wxCoord minSize) [inline]
Sets minimal size (width for column, height for row) for header cell.
Parameters:
minSize new minimal size
Returns:
reference to itself
wxAdvHdrCellRenderer* wxAdvHdrCell::Renderer () [inline]
Returns renderer to draw cell content.
Returns:
renderer
wxAdvHdrCell& wxAdvHdrCell::Renderer (wxAdvHdrCellRenderer * renderer) [inline]
Sets renderer to draw cell content.
Parameters:
renderer new renderer
Returns:
reference to itself
References wxREPLACE.
wxAdvHdrCell& wxAdvHdrCell::ResizeAllowed () [inline]
Allow row/column resize by mouse.
Returns:
reference to itself
wxAdvHdrCell * wxAdvHdrCell::RightSibling ()
References wxAdvTable::GetCol(), wxAdvTable::GetRow(), m_subCells, and NULL.
wxAdvHdrCell& wxAdvHdrCell::SetSortable (bool sortable) [inline]
Marks cell as sortable or not.
Parameters:
sortable true if you want to cell be sortable, false - overwise
Returns:
reference to itself
wxAdvHdrCell& wxAdvHdrCell::SetVerticalText (bool verticalText) [inline]
Set whether to vertical text label.
Parameters:
verticalText true if you want to label be vertical
Returns:
reference to itself
wxCoord wxAdvHdrCell::Size () [inline]
Returns size.
Returns:
size
wxAdvHdrCell& wxAdvHdrCell::Size (wxCoord size) [inline]
Sets size (width for column, height for row) for header cell.
If size is not set, it will be calculated from label width/height
Parameters:
size new size
Returns:
reference to itself
wxAdvHdrCell& wxAdvHdrCell::Sortable () [inline]
Marks cell as sortable.
Returns:
reference to itself
wxCoord wxAdvHdrCell::Spacing () [inline]
Returns spacing - distance between edges and cell content.
Returns:
spacing
wxAdvHdrCell& wxAdvHdrCell::Spacing (wxCoord spacing) [inline]
Sets distance between edges and cell content.
Parameters:
spacing distance between edges and cell content.
Returns:
reference to itself
wxAdvHdrCell& wxAdvHdrCell::Sub (const wxChar * label) [inline]
Adds sub row/column.
Parameters:
label label for sub row/column
Returns:
reference to itself
wxAdvHdrCell& wxAdvHdrCell::Sub (wxAdvHdrCell subHdrCell) [inline]
Adds sub row/column.
Parameters:
subHdrCell sub row/column
Returns:
reference to itself
References m_isRow, m_parent, and m_subIndex.
wxAdvHdrCell& wxAdvHdrCell::VerticalText () [inline]
Marks cell to draw label vertical.
Returns:
reference to itself
Friends And Related Function Documentation
friend class wxAdvDefaultHdrCellRenderer [friend]
friend class wxAdvTable [friend]
Member Data Documentation
const int wxAdvHdrCell::defaultAlignHorizontal = wxALIGN_CENTER_HORIZONTAL [static]
const int wxAdvHdrCell::defaultAlignVertical = wxALIGN_CENTER_VERTICAL [static]
const int wxAdvHdrCell::defaultSpacing = 5 [static]
The documentation for this class was generated from the following files:
wxadvtable.h
wxadvtable.cpp