wxAdvTable: wxAdvDefaultHdrCellRenderer Class Reference
wxAdvDefaultHdrCellRenderer Class Reference
Standard header cell renderer.
#include <wxadvtable.h>
Public Member Functions
wxAdvDefaultHdrCellRenderer ()
virtual ~wxAdvDefaultHdrCellRenderer ()
virtual void Draw (wxAdvTable *table, wxDC &dc, wxAdvHdrCell *hdrCell, bool selected, bool pressed, int sortDirection)
Called to draw header cell.
virtual wxAdvHdrCellRenderer * Clone ()
Returns copy of this renderer.
void SetDrawGradient (bool drawGradient)
Sets whether to draw gradient header cells.
Protected Member Functions
virtual void DrawBackground (wxDC &dc, wxAdvHdrCell *hdrCell, bool selected, bool pressed)
Protected Attributes
int m_edgeWidth
bool m_drawGradient
Detailed Description
Standard header cell renderer.
Constructor & Destructor Documentation
wxAdvDefaultHdrCellRenderer::wxAdvDefaultHdrCellRenderer ()
References m_drawGradient, and m_edgeWidth.
Referenced by Clone().
wxAdvDefaultHdrCellRenderer::~wxAdvDefaultHdrCellRenderer () [virtual]
Member Function Documentation
wxAdvHdrCellRenderer * wxAdvDefaultHdrCellRenderer::Clone () [virtual]
Returns copy of this renderer.
Implements wxAdvHdrCellRenderer.
References wxAdvDefaultHdrCellRenderer().
virtual void wxAdvDefaultHdrCellRenderer::Draw (wxAdvTable * table, wxDC & dc, wxAdvHdrCell * hdrCell, bool selected, bool pressed, int sortDirection) [virtual]
Called to draw header cell.
Parameters:
table wxAdvTable
dc device context
hdrCell header cell to draw
selected true if header cell is selected
pressed true if header cell is pressed
sortDirection sort direction
Implements wxAdvHdrCellRenderer.
void wxAdvDefaultHdrCellRenderer::DrawBackground (wxDC & dc, wxAdvHdrCell * hdrCell, bool selected, bool pressed) [protected, virtual]
References Darker(), DrawBevel(), m_drawGradient, m_edgeWidth, and wxAdvHdrCell::m_rc.
void wxAdvDefaultHdrCellRenderer::SetDrawGradient (bool drawGradient) [inline]
Sets whether to draw gradient header cells.
Parameters:
drawGradient true to draw gradient header cells
Member Data Documentation
bool wxAdvDefaultHdrCellRenderer::m_drawGradient [protected]
Referenced by DrawBackground(), and wxAdvDefaultHdrCellRenderer().
int wxAdvDefaultHdrCellRenderer::m_edgeWidth [protected]
Referenced by DrawBackground(), and wxAdvDefaultHdrCellRenderer().
The documentation for this class was generated from the following files:
wxadvtable.h
wxadvtable.cpp