wxAdvTable: wxAdvIntervalCellEditor Class Reference
wxAdvIntervalCellEditor Class Reference
Editor for interval numeric data.
#include <wxadvtable.h>
Public Member Functions
wxAdvIntervalCellEditor (wxAdvTable *table)
virtual ~wxAdvIntervalCellEditor ()
virtual bool OneClickActivate ()
Return true, if editor activated with one click (such as boolean cells editor).
void SetRange (int minValue, int maxValue)
Protected Member Functions
virtual void DoActivate ()
virtual void DoDeactivate ()
Detailed Description
Editor for interval numeric data.
Uses wxSpinCtrl for editing.
Constructor & Destructor Documentation
wxAdvIntervalCellEditor::wxAdvIntervalCellEditor (wxAdvTable * table)
wxAdvIntervalCellEditor::~wxAdvIntervalCellEditor () [virtual]
Member Function Documentation
void wxAdvIntervalCellEditor::DoActivate () [protected, virtual]
Implements wxAdvCellEditor.
References wxAdvCellEditor::GetCellRect(), wxAdvCellEditor::GetTable(), and wxAdvCellEditor::GetValue().
void wxAdvIntervalCellEditor::DoDeactivate () [protected, virtual]
Implements wxAdvCellEditor.
References wxAdvCellEditor::SetNewValue().
bool wxAdvIntervalCellEditor::OneClickActivate () [virtual]
Return true, if editor activated with one click (such as boolean cells editor).
Reimplemented from wxAdvCellEditor.
void wxAdvIntervalCellEditor::SetRange (int minValue, int maxValue)
The documentation for this class was generated from the following files:
wxadvtable.h
wxadvtable.cpp