wxAdvTable: wxadvtable.cpp File Reference
wxadvtable.cpp File Reference
#include "wx/wxadvtable.h"
#include <wx/renderer.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colordlg.h>
#include "checkMark.xpm"
#include "rowSortAscend.xpm"
#include "rowSortDescend.xpm"
#include "colSortAscend.xpm"
#include "colSortDescend.xpm"
#include <wx/arrimpl.cpp>
Classes
class SortHelper
Defines
#define ID_COMBO 5000
Functions
WX_DEFINE_EXPORTED_OBJARRAY (wxAdvHdrCellArray)
WX_DEFINE_EXPORTED_OBJARRAY (wxAdvHdrCellPtrArray)
WX_DEFINE_EXPORTED_OBJARRAY (wxAdvRangeArray)
WX_DEFINE_EXPORTED_OBJARRAY (wxCoordArray)
WX_DEFINE_EXPORTED_OBJARRAY (wxIndexArray)
WX_DEFINE_EXPORTED_OBJARRAY (wxArrayArrayString)
WX_DEFINE_EXPORTED_OBJARRAY (wxIntArray)
WX_DEFINE_EXPORTED_OBJARRAY (wxIntIntArray)
void LoadBitmaps ()
void ResizeBitmap (wxBitmap &bmp, wxCoord newWidth, wxCoord newHeight)
wxColour Darker (wxColour colour)
Make colour darker.
wxColour Brighter (wxColour colour)
Make colour brighter.
void DrawBevel (wxDC &dc, const wxRect &rc, wxColour bgColour, wxColour colour1, wxColour colour2, int edgeWidth, bool gradient)
Draws bevel.
void AlignAdjust (const wxRect &rc, wxCoord *x, wxCoord *y, wxCoord widthText, wxCoord heightText, int align, bool vertical)
void DrawMultilineText (wxDC &dc, const wxString &text, const wxRect &rc, int align, bool vertical)
Draws multiline text, using current font and text colour.
WX_DEFINE_SORTED_ARRAY (SortHelper *, wxSortHelperArray)
int SorterFunc (SortHelper *first, SortHelper *second)
Define Documentation
#define ID_COMBO 5000
Function Documentation
void AlignAdjust (const wxRect & rc, wxCoord * x, wxCoord * y, wxCoord widthText, wxCoord heightText, int align, bool vertical)
Referenced by DrawMultilineText().
wxColour Brighter (wxColour colour)
Make colour brighter.
Parameters:
colour input colour
Returns:
modified colour
Referenced by DrawBevel().
wxColour Darker (wxColour colour)
Make colour darker.
Parameters:
colour input colour
Returns:
modified colour
Referenced by wxAdvDefaultHdrCellRenderer::DrawBackground().
void DrawBevel (wxDC & dc, const wxRect & rc, wxColour bgColour, wxColour colour1, wxColour colour2, int edgeWidth, bool gradient)
Draws bevel.
Parameters:
dc device context
rc rectangle where to draw
bgColour bevel background colour
colour1 colour of left and top edges
colour2 colour of right and bottom edges
edgeWidth edgeWidth
gradient true to draw gradient bevel
References Brighter().
Referenced by wxAdvDefaultHdrCellRenderer::DrawBackground().
void DrawMultilineText (wxDC & dc, const wxString & text, const wxRect & rc, int align, bool vertical)
Draws multiline text, using current font and text colour.
Parameters:
dc device context
text text to draw
rc rectangle where to draw text
align horizontal and vertical alignment
vertical true if you want draw draw vertical text
References AlignAdjust(), and NULL.
void LoadBitmaps ()
void ResizeBitmap (wxBitmap & bmp, wxCoord newWidth, wxCoord newHeight)
int SorterFunc (SortHelper * first, SortHelper * second)
References wxAdvTableSorter::Compare(), SortHelper::m_col, SortHelper::m_row, SortHelper::m_sortDirection, SortHelper::m_sorter, SortHelper::m_table, and wxAdvTable::SortDirDescending.
WX_DEFINE_EXPORTED_OBJARRAY (wxIntIntArray)
WX_DEFINE_EXPORTED_OBJARRAY (wxIntArray)
WX_DEFINE_EXPORTED_OBJARRAY (wxArrayArrayString)
WX_DEFINE_EXPORTED_OBJARRAY (wxIndexArray)
WX_DEFINE_EXPORTED_OBJARRAY (wxCoordArray)
WX_DEFINE_EXPORTED_OBJARRAY (wxAdvRangeArray)
WX_DEFINE_EXPORTED_OBJARRAY (wxAdvHdrCellPtrArray)
WX_DEFINE_EXPORTED_OBJARRAY (wxAdvHdrCellArray)
WX_DEFINE_SORTED_ARRAY (SortHelper * , wxSortHelperArray)