# Generated automatically from Makefile.in by configure.
#
# File:		makefile.unx
# Author:	Julian Smart
# Created:	1998
# Updated:	
# Copyright:	(c) 1998 Julian Smart
#
# "%W% %G%"
#
# Makefile for custom example (UNIX).
# copied from /samples/minimal

top_srcdir = ../..
top_builddir = ../..
program_dir = samples/custom

PROGRAM=minimal

OBJECTS=$(PROGRAM).o toggle.o

include ../../src/makeprog.env

