#
# File:		makefile.vc
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:	(c) Julian Smart
#
# Makefile : Builds sample (VC++, WIN32)
# Use FINAL=1 argument to nmake to build final version with no debug info.

# Set WXDIR for your system
WXDIR = $(WXWIN)

PROGRAM=awtlayouts
OBJECTS = awt_emul.obj cardlayout.obj boxlayout.obj flowlayout.obj borderlayout.obj gridlayout.obj absolutelayout.obj gridbaglayout.obj layout_test.obj 

!include $(WXDIR)\src\makeprog.vc


