# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.6 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================




prefix = /usr/local
exec_prefix = ${prefix}
datarootdir = @datarootdir@
INSTALL = /usr/bin/install -c
SHARED_LD_CXX = $(CXX) -shared -fPIC -o
LIBEXT = .a
LIBPREFIX = lib
SO_SUFFIX = so
DLLIMP_SUFFIX = so
LN_S = ln -s
PIC_FLAG = -fPIC -DPIC
SONAME_FLAG = -Wl,-soname,
STRIP = strip
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_DIR = $(INSTALL) -d
BK_DEPS = /home/luciano/sf/wxCode/components/wxjson/bk-deps
srcdir = .
libdir = ${exec_prefix}/lib
DLLPREFIX = lib
LIBS = 
AR = ar
AROPTIONS = rcu
RANLIB = ranlib
CXX = g++
CXXFLAGS =  -g -O0
CPPFLAGS = 
LDFLAGS = 
WX_CXXFLAGS = -I/usr/local/lib/wx/include/gtk2-ansi-debug-2.8 -I/usr/local/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXDEBUG__ -D__WXGTK__ -pthread -fno-rtti -fno-exceptions
WX_LIBS = -L/usr/local/lib -pthread   -lwx_gtk2d_core-2.8 -lwx_based-2.8 
WX_VERSION_MAJOR = 2
WX_VERSION_MINOR = 8
WX_PORT = gtk2

### Variables: ###

DESTDIR = 
WXJSON_LIB_CXXFLAGS = -I$(srcdir)/include $(WX_CXXFLAGS) $(CPPFLAGS) \
	$(CXXFLAGS)
WXJSON_LIB_OBJECTS =  \
	wxjson_lib_jsonreader.o \
	wxjson_lib_jsonval.o \
	wxjson_lib_jsonwriter.o
WXJSON_LIB_HEADERS =  \
	include/wx/json_defs.h \
	include/wx/jsonreader.h \
	include/wx/jsonval.h \
	include/wx/jsonwriter.h
WXJSON_DLL_CXXFLAGS = -I$(srcdir)/include -DWXMAKINGDLL_WXJSON $(PIC_FLAG) \
	$(WX_CXXFLAGS) $(CPPFLAGS) $(CXXFLAGS)
WXJSON_DLL_OBJECTS =  \
	wxjson_dll_jsonreader.o \
	wxjson_dll_jsonval.o \
	wxjson_dll_jsonwriter.o
WXJSON_DLL_HEADERS =  \
	include/wx/json_defs.h \
	include/wx/jsonreader.h \
	include/wx/jsonval.h \
	include/wx/jsonwriter.h

### Conditionally set variables: ###

#CXXC = $(CXX)
CXXC = $(BK_DEPS) $(CXX)
#WXLIBPOSTFIX = u
WXLIBPOSTFIX = d
#WXLIBPOSTFIX = ud
COND_WX_SHARED_0___wxjson_lib___depname = \
	$(srcdir)/lib/$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(LIBEXT)
#__wxjson_lib___depname = $(COND_WX_SHARED_0___wxjson_lib___depname)
#__install_wxjson_lib___depname = install_wxjson_lib
#__uninstall_wxjson_lib___depname = uninstall_wxjson_lib
#__install_wxjson_lib_headers___depname \
#	= install_wxjson_lib_headers
#__uninstall_wxjson_lib_headers___depname \
#	= uninstall_wxjson_lib_headers
COND_WX_SHARED_1___wxjson_dll___depname = \
	$(srcdir)/lib/$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf3)
__wxjson_dll___depname = $(COND_WX_SHARED_1___wxjson_dll___depname)
__install_wxjson_dll___depname = install_wxjson_dll
__uninstall_wxjson_dll___depname = uninstall_wxjson_dll
COND_PLATFORM_MACOSX_1___wxjson_dll___macinstnamecmd = -install_name \
	$(libdir)/$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf2)
#__wxjson_dll___macinstnamecmd = $(COND_PLATFORM_MACOSX_1___wxjson_dll___macinstnamecmd)
COND_PLATFORM_OS2_1___wxjson_dll___importlib = -import \
	$(srcdir)/lib/$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR).$(DLLIMP_SUFFIX)
#__wxjson_dll___importlib = $(COND_PLATFORM_OS2_1___wxjson_dll___importlib)
COND_WINDOWS_IMPLIB_1___wxjson_dll___importlib = \
	-Wl,--out-implib=$(srcdir)/lib/$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR).$(DLLIMP_SUFFIX)
#__wxjson_dll___importlib = $(COND_WINDOWS_IMPLIB_1___wxjson_dll___importlib)
__wxjson_dll___targetsuf2 \
	= .$(SO_SUFFIX).0
#__wxjson_dll___targetsuf2 \
#	= .0.$(SO_SUFFIX)
#__wxjson_dll___targetsuf2 = .$(SO_SUFFIX)
__wxjson_dll___targetsuf3 \
	= \
	.$(SO_SUFFIX).0.0.0
#__wxjson_dll___targetsuf3 \
#	= .0.0.0.$(SO_SUFFIX)
#__wxjson_dll___targetsuf3 \
#	= -0.$(SO_SUFFIX)
#__wxjson_dll___targetsuf3 = .$(SO_SUFFIX)
COND_USE_SOVERLINUX_1___wxjson_dll___soname_flags = \
	$(SONAME_FLAG)$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf2)
__wxjson_dll___soname_flags = $(COND_USE_SOVERLINUX_1___wxjson_dll___soname_flags)
COND_USE_SOVERSOLARIS_1___wxjson_dll___soname_flags = \
	$(SONAME_FLAG)$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf3)
#__wxjson_dll___soname_flags = $(COND_USE_SOVERSOLARIS_1___wxjson_dll___soname_flags)
COND_USE_SOSYMLINKS_1___wxjson_dll___so_symlinks_cmd = (cd $(srcdir)/lib/; rm \
	-f \
	$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR).$(DLLIMP_SUFFIX) \
	$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf2); \
	$(LN_S) \
	$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf3) \
	$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf2); \
	$(LN_S) \
	$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf2) \
	$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR).$(DLLIMP_SUFFIX))
__wxjson_dll___so_symlinks_cmd = $(COND_USE_SOSYMLINKS_1___wxjson_dll___so_symlinks_cmd)
COND_USE_SOSYMLINKS_1___wxjson_dll___so_symlinks_inst_cmd = rm -f \
	$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR).$(DLLIMP_SUFFIX) \
	$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf2); \
	$(LN_S) \
	$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf3) \
	$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf2); \
	$(LN_S) \
	$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf2) \
	$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR).$(DLLIMP_SUFFIX)
__wxjson_dll___so_symlinks_inst_cmd = $(COND_USE_SOSYMLINKS_1___wxjson_dll___so_symlinks_inst_cmd)
COND_USE_SOSYMLINKS_1___wxjson_dll___so_symlinks_uninst_cmd = rm -f \
	$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf2) \
	$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR).$(DLLIMP_SUFFIX)
__wxjson_dll___so_symlinks_uninst_cmd = $(COND_USE_SOSYMLINKS_1___wxjson_dll___so_symlinks_uninst_cmd)
__install_wxjson_dll_headers___depname \
	= install_wxjson_dll_headers
__uninstall_wxjson_dll_headers___depname \
	= uninstall_wxjson_dll_headers

### Targets: ###

all: $(__wxjson_lib___depname) $(__wxjson_dll___depname)

install: $(__install_wxjson_lib___depname) $(__install_wxjson_lib_headers___depname) $(__install_wxjson_dll___depname) $(__install_wxjson_dll_headers___depname)

uninstall: $(__uninstall_wxjson_lib___depname) $(__uninstall_wxjson_lib_headers___depname) $(__uninstall_wxjson_dll___depname) $(__uninstall_wxjson_dll_headers___depname)

install-strip: install
	$(STRIP) $(DESTDIR)$(libdir)/$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf3)

clean: 
	rm -rf ./.deps ./.pch
	rm -f ./*.o
	rm -f $(srcdir)/lib/$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(LIBEXT)
	rm -f $(srcdir)/lib/$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf3)
	rm -f $(srcdir)/lib/$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR).$(DLLIMP_SUFFIX)
	rm -f $(srcdir)/lib/$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR).$(DLLIMP_SUFFIX) $(srcdir)/lib/$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf2)

distclean: clean
	rm -f config.cache config.log config.status bk-deps bk-make-pch shared-ld-sh Makefile

#$(srcdir)/lib/$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(LIBEXT): $(WXJSON_LIB_OBJECTS)
#	rm -f $@
#	$(AR) $(AROPTIONS) $@ $(WXJSON_LIB_OBJECTS)
#	$(RANLIB) $@

#install_wxjson_lib: $(__wxjson_lib___depname)
#	$(INSTALL_DIR) $(DESTDIR)$(libdir)
#	$(INSTALL_DATA) $(srcdir)/lib/$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(LIBEXT) $(DESTDIR)$(libdir)

#uninstall_wxjson_lib: 
#	rm -f $(DESTDIR)$(libdir)/$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(LIBEXT)

#install_wxjson_lib_headers: 
#	$(INSTALL_DIR) $(DESTDIR)$(prefix)
#	for f in $(WXJSON_LIB_HEADERS); do \
#	if test ! -d $(DESTDIR)$(prefix)/`dirname $$f` ; then \
#	$(INSTALL_DIR) $(DESTDIR)$(prefix)/`dirname $$f`; \
#	fi; \
#	$(INSTALL_DATA) $(srcdir)/$$f $(DESTDIR)$(prefix)/$$f; \
#	done

#uninstall_wxjson_lib_headers: 
#	for f in $(WXJSON_LIB_HEADERS); do \
#	rm -f $(DESTDIR)$(prefix)/$$f; \
#	done

$(srcdir)/lib/$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf3): $(WXJSON_DLL_OBJECTS)
	$(SHARED_LD_CXX) $@ $(WXJSON_DLL_OBJECTS)  -L$(srcdir)/lib $(__wxjson_dll___macinstnamecmd) $(__wxjson_dll___importlib) $(__wxjson_dll___soname_flags) $(LDFLAGS)  $(WX_LIBS) $(LIBS)
	
	$(__wxjson_dll___so_symlinks_cmd)

install_wxjson_dll: $(__wxjson_dll___depname)
	$(INSTALL_DIR) $(DESTDIR)$(libdir)
	$(INSTALL_DATA) $(srcdir)/lib/$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR).$(DLLIMP_SUFFIX) $(DESTDIR)$(libdir)
	$(INSTALL_PROGRAM) $(srcdir)/lib/$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf3) $(DESTDIR)$(libdir)
	(cd $(DESTDIR)$(libdir) ; $(__wxjson_dll___so_symlinks_inst_cmd))

uninstall_wxjson_dll: 
	rm -f $(DESTDIR)$(libdir)/$(LIBPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR).$(DLLIMP_SUFFIX)
	rm -f $(DESTDIR)$(libdir)/$(DLLPREFIX)wxcode_$(WX_PORT)$(WXLIBPOSTFIX)_wxjson-$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)$(__wxjson_dll___targetsuf3)
	(cd $(DESTDIR)$(libdir) ; $(__wxjson_dll___so_symlinks_uninst_cmd))

install_wxjson_dll_headers: 
	$(INSTALL_DIR) $(DESTDIR)$(prefix)
	for f in $(WXJSON_DLL_HEADERS); do \
	if test ! -d $(DESTDIR)$(prefix)/`dirname $$f` ; then \
	$(INSTALL_DIR) $(DESTDIR)$(prefix)/`dirname $$f`; \
	fi; \
	$(INSTALL_DATA) $(srcdir)/$$f $(DESTDIR)$(prefix)/$$f; \
	done

uninstall_wxjson_dll_headers: 
	for f in $(WXJSON_DLL_HEADERS); do \
	rm -f $(DESTDIR)$(prefix)/$$f; \
	done

wxjson_lib_jsonreader.o: $(srcdir)/src/jsonreader.cpp
	$(CXXC) -c -o $@ $(WXJSON_LIB_CXXFLAGS) $(srcdir)/src/jsonreader.cpp

wxjson_lib_jsonval.o: $(srcdir)/src/jsonval.cpp
	$(CXXC) -c -o $@ $(WXJSON_LIB_CXXFLAGS) $(srcdir)/src/jsonval.cpp

wxjson_lib_jsonwriter.o: $(srcdir)/src/jsonwriter.cpp
	$(CXXC) -c -o $@ $(WXJSON_LIB_CXXFLAGS) $(srcdir)/src/jsonwriter.cpp

wxjson_dll_jsonreader.o: $(srcdir)/src/jsonreader.cpp
	$(CXXC) -c -o $@ $(WXJSON_DLL_CXXFLAGS) $(srcdir)/src/jsonreader.cpp

wxjson_dll_jsonval.o: $(srcdir)/src/jsonval.cpp
	$(CXXC) -c -o $@ $(WXJSON_DLL_CXXFLAGS) $(srcdir)/src/jsonval.cpp

wxjson_dll_jsonwriter.o: $(srcdir)/src/jsonwriter.cpp
	$(CXXC) -c -o $@ $(WXJSON_DLL_CXXFLAGS) $(srcdir)/src/jsonwriter.cpp


# Include dependency info, if present:
-include ./.deps/*.d

.PHONY: all install uninstall clean distclean install_wxjson_lib \
	uninstall_wxjson_lib install_wxjson_lib_headers \
	uninstall_wxjson_lib_headers install_wxjson_dll uninstall_wxjson_dll \
	install_wxjson_dll_headers uninstall_wxjson_dll_headers
