/////////////////////////////////////////////////////////////////////////////
// Name:        DatabaseConnectionDlg.h
// Purpose:     
// Author:      Matías Szeftel
// Modified by: 
// Created:     Fri 09 Feb 2007 00:58:02 ART
// RCS-ID:      
// Copyright:   (c) 2006 Matías Szeftel <mszeftel@yahoo.com.ar>
// Licence:     GPL (GNU Public License)
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), Fri 09 Feb 2007 00:58:02 ART

#ifndef _DATABASECONNECTIONDLG_H_
#define _DATABASECONNECTIONDLG_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "DatabaseConnectionDlg.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

#include "wxActiveRecordGenerator.h"

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CONNECTIONDLG 10018
#define ID_CMBTYPE 10020
#define ID_TCSERVER 10021
#define ID_TCDATABASE 10022
#define ID_BTNFILE 10024
#define ID_TCUSER 10023
#define ID_TCPASSWORD 10025
#define ID_CONNECT 10026
#define SYMBOL_DATABASECONNECTIONDLG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_DATABASECONNECTIONDLG_TITLE _("Database Conection")
#define SYMBOL_DATABASECONNECTIONDLG_IDNAME ID_CONNECTIONDLG
#define SYMBOL_DATABASECONNECTIONDLG_SIZE wxSize(400, 300)
#define SYMBOL_DATABASECONNECTIONDLG_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * DatabaseConnectionDlg class declaration
 */

class DatabaseConnectionDlg: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( DatabaseConnectionDlg )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    DatabaseConnectionDlg( );
    DatabaseConnectionDlg( wxWindow* parent, wxWindowID id = SYMBOL_DATABASECONNECTIONDLG_IDNAME, const wxString& caption = SYMBOL_DATABASECONNECTIONDLG_TITLE, const wxPoint& pos = SYMBOL_DATABASECONNECTIONDLG_POSITION, const wxSize& size = SYMBOL_DATABASECONNECTIONDLG_SIZE, long style = SYMBOL_DATABASECONNECTIONDLG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_DATABASECONNECTIONDLG_IDNAME, const wxString& caption = SYMBOL_DATABASECONNECTIONDLG_TITLE, const wxPoint& pos = SYMBOL_DATABASECONNECTIONDLG_POSITION, const wxSize& size = SYMBOL_DATABASECONNECTIONDLG_SIZE, long style = SYMBOL_DATABASECONNECTIONDLG_STYLE );

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin DatabaseConnectionDlg event handler declarations

    /// wxEVT_UPDATE_UI event handler for ID_TCSERVER
    void OnTcserverUpdate( wxUpdateUIEvent& event );

    /// wxEVT_UPDATE_UI event handler for ID_TCDATABASE
    void OnTcdatabaseUpdate( wxUpdateUIEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BTNFILE
    void OnBtnfileClick( wxCommandEvent& event );

    /// wxEVT_UPDATE_UI event handler for ID_BTNFILE
    void OnBtnfileUpdate( wxUpdateUIEvent& event );

    /// wxEVT_UPDATE_UI event handler for ID_TCUSER
    void OnTcuserUpdate( wxUpdateUIEvent& event );

    /// wxEVT_UPDATE_UI event handler for ID_TCPASSWORD
    void OnTcpasswordUpdate( wxUpdateUIEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_CONNECT
    void OnConnectClick( wxCommandEvent& event );

    /// wxEVT_UPDATE_UI event handler for ID_CONNECT
    void OnConnectUpdate( wxUpdateUIEvent& event );

////@end DatabaseConnectionDlg event handler declarations

////@begin DatabaseConnectionDlg member function declarations

    wxActiveRecordGenerator* GetActiveRecordGen() const { return activeRecordGen ; }
    void SetActiveRecordGen(wxActiveRecordGenerator* value) { activeRecordGen = value ; }

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end DatabaseConnectionDlg member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin DatabaseConnectionDlg member variables
    wxComboBox* cmb_type;
    wxTextCtrl* tc_server;
    wxTextCtrl* tc_database;
    wxButton* btn_file;
    wxTextCtrl* tc_user;
    wxTextCtrl* tc_password;
    wxButton* btn_connect;
    wxButton* btn_cancel;
    wxActiveRecordGenerator* activeRecordGen;
////@end DatabaseConnectionDlg member variables
};

#endif
    // _DATABASECONNECTIONDLG_H_
