# WXXT base directory
WXBASEDIR=/home/alex/wxgtk

# set the OS type for compilation
OS=Linux
# compile a library only
RULE=bin

# define library name
BIN_TARGET=awtlayouts

# define library sources
BIN_SRC= awt_emul.cpp cardlayout.cpp boxlayout.cpp flowlayout.cpp borderlayout.cpp gridlayout.cpp absolutelayout.cpp gridbaglayout.cpp layout_test.cpp


#define library objects
BIN_OBJ= awt_emul.o cardlayout.o boxlayout.o flowlayout.o borderlayout.o gridlayout.o absolutelayout.o gridbaglayout.o layout_test.o


# additional things needed to link
BIN_LINK=

# additional things needed to compile
ADD_COMPILE=

# include the definitions now
include ../../../template.mak
