//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: prefs.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_prefs_H__
#define __WDR_prefs_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "prefs_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT = 10000;
const int ID_NAME = 10001;
const int ID_POSITION = 10002;
const int ID_ADDRESS = 10003;
const int ID_PHONE = 10004;
const int ID_EMAIL = 10005;
wxSizer *User( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_GROUP = 10006;
wxSizer *Group( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
