wxAdvTable: wxAdvCellEditor Class Reference
wxAdvCellEditor Class Reference
Table cell editors base class.
#include <wxadvtable.h>
Public Member Functions
wxAdvCellEditor (wxAdvTable *table)
virtual ~wxAdvCellEditor ()
virtual bool OneClickActivate ()
Return true, if editor activated with one click (such as boolean cells editor).
void Activate (size_t row, size_t col)
Called to activate cell editor.
void Deactivate ()
Called to deactivate cell editor.
bool IsActive ()
Checks whether editor is active.
virtual void HandleKeyEvent (wxKeyEvent &ev)
Called to handle key event, that triggers editor activation.
Protected Member Functions
virtual void DoActivate ()=0
virtual void DoDeactivate ()=0
wxAdvTable * GetTable ()
size_t GetRow ()
size_t GetCol ()
wxRect GetCellRect ()
wxString GetValue ()
void SetNewValue (wxString newValue)
void EndEditing ()
Call this when editor initiate self deactivation.
Detailed Description
Table cell editors base class.
Editor is an object, that perform cell values editing, it activated from wxAdvTable on mouse click or keypress, and deactivated when user wants to edit another cell or when wxAdvTable losses keyboard focus.
Constructor & Destructor Documentation
wxAdvCellEditor::wxAdvCellEditor (wxAdvTable * table)
wxAdvCellEditor::~wxAdvCellEditor () [virtual]
Member Function Documentation
void wxAdvCellEditor::Activate (size_t row, size_t col)
Called to activate cell editor.
Parameters:
row row index
col column index
References DoActivate(), and wxAdvCoord::Set().
void wxAdvCellEditor::Deactivate ()
Called to deactivate cell editor.
Parameters:
table wxAdvTable
References DoDeactivate(), and wxAdvCoord::Unset().
Referenced by wxAdvTable::StopEditing().
virtual void wxAdvCellEditor::DoActivate () [protected, pure virtual]
Implemented in wxAdvStringCellEditor, wxAdvBoolCellEditor, wxAdvColourCellEditor, wxAdvIntervalCellEditor, and wxAdvChoicesCellEditor.
Referenced by Activate().
virtual void wxAdvCellEditor::DoDeactivate () [protected, pure virtual]
Implemented in wxAdvStringCellEditor, wxAdvBoolCellEditor, wxAdvColourCellEditor, wxAdvIntervalCellEditor, and wxAdvChoicesCellEditor.
Referenced by Deactivate().
void wxAdvCellEditor::EndEditing () [protected]
Call this when editor initiate self deactivation.
References NULL, and wxAdvTable::StopEditing().
Referenced by wxAdvColourCellEditor::DoActivate(), and wxAdvBoolCellEditor::DoActivate().
wxRect wxAdvCellEditor::GetCellRect () [protected]
References wxAdvCoord::Col(), wxAdvTable::GetCellRect(), wxAdvCoord::IsSet(), and wxAdvCoord::Row().
Referenced by wxAdvChoicesCellEditor::DoActivate(), wxAdvIntervalCellEditor::DoActivate(), and wxAdvStringCellEditor::DoActivate().
size_t wxAdvCellEditor::GetCol () [protected]
References wxAdvCoord::Col(), wxAdvCoord::IsSet(), and UNDEF_SIZE.
size_t wxAdvCellEditor::GetRow () [protected]
References wxAdvCoord::IsSet(), wxAdvCoord::Row(), and UNDEF_SIZE.
wxAdvTable * wxAdvCellEditor::GetTable () [protected]
Referenced by wxAdvChoicesCellEditor::DoActivate(), wxAdvIntervalCellEditor::DoActivate(), wxAdvColourCellEditor::DoActivate(), and wxAdvStringCellEditor::DoActivate().
wxString wxAdvCellEditor::GetValue () [protected]
References wxAdvCoord::Col(), wxAdvTable::GetCellValue(), wxAdvCoord::IsSet(), and wxAdvCoord::Row().
Referenced by wxAdvChoicesCellEditor::DoActivate(), wxAdvIntervalCellEditor::DoActivate(), wxAdvColourCellEditor::DoActivate(), wxAdvBoolCellEditor::DoActivate(), and wxAdvStringCellEditor::DoActivate().
virtual void wxAdvCellEditor::HandleKeyEvent (wxKeyEvent & ev) [virtual]
Called to handle key event, that triggers editor activation.
Called by wxAdvTable if cell editing activated by key press.
Reimplemented in wxAdvStringCellEditor.
bool wxAdvCellEditor::IsActive ()
Checks whether editor is active.
Returns:
true if editor is active
bool wxAdvCellEditor::OneClickActivate () [virtual]
Return true, if editor activated with one click (such as boolean cells editor).
Reimplemented in wxAdvStringCellEditor, wxAdvBoolCellEditor, wxAdvColourCellEditor, wxAdvIntervalCellEditor, and wxAdvChoicesCellEditor.
void wxAdvCellEditor::SetNewValue (wxString newValue) [protected]
References wxAdvTable::ChangeCellValue(), wxAdvCoord::Col(), wxAdvCoord::IsSet(), NULL, wxAdvCoord::Row(), and wxAdvTable::ToModelCellCoord().
Referenced by wxAdvColourCellEditor::DoActivate(), wxAdvBoolCellEditor::DoActivate(), wxAdvIntervalCellEditor::DoDeactivate(), and wxAdvStringCellEditor::DoDeactivate().
The documentation for this class was generated from the following files:
wxadvtable.h
wxadvtable.cpp