wxAdvTable: wxAdvStringCellEditor Class Reference
wxAdvStringCellEditor Class Reference
Editor for string cell values.
#include <wxadvtable.h>
Public Member Functions
wxAdvStringCellEditor (wxAdvTable *table)
virtual ~wxAdvStringCellEditor ()
virtual bool OneClickActivate ()
Return true, if editor activated with one click (such as boolean cells editor).
virtual void HandleKeyEvent (wxKeyEvent &ev)
Called to handle key event, that triggers editor activation.
Protected Member Functions
virtual void DoActivate ()
virtual void DoDeactivate ()
Detailed Description
Editor for string cell values.
Uses wxTextCtrl for text input.
Constructor & Destructor Documentation
wxAdvStringCellEditor::wxAdvStringCellEditor (wxAdvTable * table)
wxAdvStringCellEditor::~wxAdvStringCellEditor () [virtual]
Member Function Documentation
void wxAdvStringCellEditor::DoActivate () [protected, virtual]
Implements wxAdvCellEditor.
References wxAdvCellEditor::GetCellRect(), wxAdvCellEditor::GetTable(), and wxAdvCellEditor::GetValue().
void wxAdvStringCellEditor::DoDeactivate () [protected, virtual]
Implements wxAdvCellEditor.
References wxAdvCellEditor::SetNewValue().
void wxAdvStringCellEditor::HandleKeyEvent (wxKeyEvent & ev) [virtual]
Called to handle key event, that triggers editor activation.
Called by wxAdvTable if cell editing activated by key press.
Reimplemented from wxAdvCellEditor.
bool wxAdvStringCellEditor::OneClickActivate () [virtual]
Return true, if editor activated with one click (such as boolean cells editor).
Reimplemented from wxAdvCellEditor.
The documentation for this class was generated from the following files:
wxadvtable.h
wxadvtable.cpp