wxAdvTable: wxAdvTableDateTimeSorter Class Reference
wxAdvTableDateTimeSorter Class Reference
Sorts data by comparing datetime values.
#include <wxadvtable.h>
Public Member Functions
wxAdvTableDateTimeSorter ()
virtual ~wxAdvTableDateTimeSorter ()
virtual int Compare (wxAdvTable *table, size_t row1, size_t col1, size_t row2, size_t col2)
Detailed Description
Sorts data by comparing datetime values.
Constructor & Destructor Documentation
wxAdvTableDateTimeSorter::wxAdvTableDateTimeSorter ()
wxAdvTableDateTimeSorter::~wxAdvTableDateTimeSorter () [virtual]
Member Function Documentation
int wxAdvTableDateTimeSorter::Compare (wxAdvTable * table, size_t row1, size_t col1, size_t row2, size_t col2) [virtual]
Reimplemented from wxAdvTableStringSorter.
References wxAdvTableDataModel::GetCellFormat(), wxAdvTableDataModel::GetCellValueAsDateTime(), wxAdvTable::GetModel(), and wxDateTimeFormat.
The documentation for this class was generated from the following files:
wxadvtable.h
wxadvtable.cpp