wxAdvTable: Observable< O > Class Template Reference
Observable< O > Class Template Reference
This template defines Observable object pattern.
#include <observable.h>
Public Types
typedef O Observer
Public Member Functions
Observable ()
void AddObserver (O *_observer)
void RemoveObserver (O *_observer)
Public Attributes
std::vector< O * >::iterator OIt
Protected Attributes
std::vector< O * > observers
Detailed Description
template<class O>
class Observable< O >
This template defines Observable object pattern.
Member Typedef Documentation
template<class O> typedef O Observable< O >::Observer
Constructor & Destructor Documentation
template<class O> Observable< O >::Observable () [inline]
Member Function Documentation
template<class O> void Observable< O >::AddObserver (O * _observer) [inline]
Referenced by wxAdvTable::Create(), and wxAdvFilterTableDataModel::wxAdvFilterTableDataModel().
template<class O> void Observable< O >::RemoveObserver (O * _observer) [inline]
Referenced by wxAdvTable::DestroyTable(), and wxAdvFilterTableDataModel::~wxAdvFilterTableDataModel().
Member Data Documentation
template<class O> std::vector<O*> Observable< O >::observers [protected]
Referenced by Observable< wxAdvTableDataModelObserver >::AddObserver(), and Observable< wxAdvTableDataModelObserver >::RemoveObserver().
template<class O> std::vector<O*>::iterator Observable< O >::OIt
The documentation for this class was generated from the following file:
observable.h