wxAdvTable: wxAdvRange Class Reference
wxAdvRange Class Reference
Represents cell range, from [row1;col1] to [row2;col2].
#include <wxadvtable.h>
Public Member Functions
wxAdvRange ()
wxAdvRange (size_t row1, size_t col1, size_t row2, size_t col2)
Constructs new range.
virtual ~wxAdvRange ()
void Set (size_t row, size_t col)
Setup range to single cell.
void Set (size_t row1, size_t col1, size_t row2, size_t col2)
Sets range.
void Unset ()
Unset range coordinates.
bool IsSet ()
Checks whether range coordinates is set.
bool Contains (size_t row, size_t col)
Determines if specified cell is in range.
bool ContainsRow (size_t row)
Determines if specified row is in range.
bool ContainsCol (size_t col)
Determines if specified column is in range.
bool IsSingleCell ()
Checks whether range contains only one cell.
bool Equals (size_t row1, size_t col1, size_t row2, size_t col2)
Checks whether this range is equals to other range.
void operator= (const wxAdvRange &o)
Sets this range equal to other range.
size_t Row1 ()
size_t Row2 ()
size_t Col1 ()
size_t Col2 ()
size_t TopRow ()
Returns top row.
size_t BottomRow ()
Returns bottom row.
size_t LeftCol ()
Returns left column.
size_t RightCol ()
Returns right column.
Detailed Description
Represents cell range, from [row1;col1] to [row2;col2].
Constructor & Destructor Documentation
wxAdvRange::wxAdvRange () [inline]
wxAdvRange::wxAdvRange (size_t row1, size_t col1, size_t row2, size_t col2) [inline]
Constructs new range.
Parameters:
row1 first row index
col1 first column index
row2 second row index
col2 second column index
virtual wxAdvRange::~wxAdvRange () [inline, virtual]
Member Function Documentation
size_t wxAdvRange::BottomRow () [inline]
Returns bottom row.
Returns:
bottom row
Referenced by wxAdvTable::ScrollToCell().
size_t wxAdvRange::Col1 () [inline]
Referenced by wxAdvTable::GetRangeRect(), and wxAdvTable::SetSelection().
size_t wxAdvRange::Col2 () [inline]
Referenced by wxAdvTable::GetRangeRect(), and wxAdvTable::SetSelection().
bool wxAdvRange::Contains (size_t row, size_t col) [inline]
Determines if specified cell is in range.
Parameters:
row row index
col column index
Returns:
true if cell in range
bool wxAdvRange::ContainsCol (size_t col) [inline]
Determines if specified column is in range.
Parameters:
col column index
Returns:
true if column in range
bool wxAdvRange::ContainsRow (size_t row) [inline]
Determines if specified row is in range.
Parameters:
row row index
Returns:
true if row in range
bool wxAdvRange::Equals (size_t row1, size_t col1, size_t row2, size_t col2) [inline]
Checks whether this range is equals to other range.
Parameters:
row1 first row index
col1 first column index
row2 second row index
col2 second column index
Returns:
true if this range is equals to other range
bool wxAdvRange::IsSet () [inline]
Checks whether range coordinates is set.
Returns:
true if range coordinates is set
References UNDEF_SIZE.
bool wxAdvRange::IsSingleCell () [inline]
Checks whether range contains only one cell.
Returns:
true if range contains only one cell
size_t wxAdvRange::LeftCol () [inline]
Returns left column.
Returns:
left column
Referenced by wxAdvTable::ScrollToCell().
void wxAdvRange::operator= (const wxAdvRange & o) [inline]
Sets this range equal to other range.
Parameters:
o other range
References m_col1, m_col2, m_row1, and m_row2.
size_t wxAdvRange::RightCol () [inline]
Returns right column.
Returns:
right column
Referenced by wxAdvTable::ScrollToCell().
size_t wxAdvRange::Row1 () [inline]
Referenced by wxAdvTable::GetRangeRect(), and wxAdvTable::SetSelection().
size_t wxAdvRange::Row2 () [inline]
Referenced by wxAdvTable::GetRangeRect(), and wxAdvTable::SetSelection().
void wxAdvRange::Set (size_t row1, size_t col1, size_t row2, size_t col2) [inline]
Sets range.
Parameters:
row1 first row index
col1 first column index
row2 second row index
col2 second column index
void wxAdvRange::Set (size_t row, size_t col) [inline]
Setup range to single cell.
Parameters:
row row index
col row index
Referenced by wxAdvTable::GetVisibleRange(), and wxAdvTable::SetSelection().
size_t wxAdvRange::TopRow () [inline]
Returns top row.
Returns:
top row
Referenced by wxAdvTable::ScrollToCell().
void wxAdvRange::Unset () [inline]
Unset range coordinates.
References UNDEF_SIZE.
Referenced by wxAdvTable::ClearSelection().
The documentation for this class was generated from the following file:
wxadvtable.h