wxAdvTable: wxAdvTable Class Reference
wxAdvTable Class Reference
Main component class.
#include <wxadvtable.h>
Public Types
enum SortMode { SortRows, SortCols, SortDisabled }
enum SelectMode { SelectCell, SelectRows, SelectCols, SelectBlock }
enum HighlightMode { HighlightNone, HighlightRows, HighlightCols, HighlightBoth }
enum SortDirection { SortDirAscending, SortDirDescending, SortDirNoSorting }
Public Member Functions
wxAdvTable (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
virtual ~wxAdvTable ()
void Create (wxAdvHdrCell *rows, size_t numRows, wxAdvHdrCell *cols, size_t numCols, const wxString &cornerLabel, wxAdvTableDataModel *model)
Create table and arrange rows and columns.
void Create (wxAdvHdrCellArray &rows, wxAdvHdrCellArray &cols, const wxString &cornerLabel, wxAdvTableDataModel *model)
Create table and arrange rows and columns.
void Create (size_t numRows, wxAdvHdrCell *cols, size_t numCols, const wxString &cornerLabel, wxAdvTableDataModel *model)
Create table and arrange rows and columns, with specified row count.
void Create (wxAdvHdrCell *rows, size_t numRows, size_t numCols, const wxString &cornerLabel, wxAdvTableDataModel *model)
Create table and arrange rows and columns, with specified column count.
void Create (size_t numRows, size_t numCols, const wxString &cornerLabel, wxAdvTableDataModel *model)
Create table and arrange rows and columns, with specified row and column count.
void DestroyTable ()
Destroy table, free data model.
void UpdateGeometry ()
Recalculate entire table geometry and repaint it.
void AddRows (wxAdvHdrCell *rows, size_t numRows, size_t before=UNDEF_SIZE)
Add rows to table.
void AddCols (wxAdvHdrCell *cols, size_t numCols, size_t before=UNDEF_SIZE)
Add columns to table.
void RemoveRows (size_t from, size_t count)
Remove rows from table.
void RemoveCols (size_t from, size_t count)
Remove columns from table.
void RemoveHdrCells (size_t from, size_t count, bool isRows)
Remove header cells from table.
void RemoveHdrCell (wxAdvHdrCell *hdrCell)
Remove header cell from table.
void SetShowHeaders (bool showRows, bool showCols, bool showCorner)
Sets headers (row, column, corner header) show params.
void SetShowRows (bool showRows)
Sets whether to show rows header.
bool GetShowRows ()
Returns true, if rows header is shown.
void SetShowCols (bool showCols)
Sets whether to show columns header.
bool GetShowCols ()
Returns true, if columns header is shown.
void SetShowCorner (bool showCorner)
Sets whether to show table corner.
bool GetShowCorner ()
Returns true, if table corner is shown.
void SetSorter (wxAdvTableSorter *sorter)
Sets sorter to sort table data.
wxAdvTableSorter * GetSorter ()
Returns sorter to sort table data.
void SetSortMode (SortMode sortMode)
Sets sorting mode (eg Rows to sort rows - vertical sort, or Cols to sort columns - horizontal sort).
SortMode GetSortMode ()
Returns current sort mode.
void SetSortingIndex (size_t sortingIndex, bool invert=true)
Sets row/column index for sorting.
size_t GetSortingIndex ()
Returns current row/column index for sorting.
void SetSortDirection (SortDirection sortDirection)
Sets sort direction.
SortDirection GetSortDirection ()
Returns current sort direction.
bool IsSorting ()
Checks whether table is sorted.
void SetAllowSortByAnyRow (bool sortByAnyRow)
Sets whether to allow sorting by any row, not only marked as sortable.
bool IsAllowSortByAnyRow ()
void SetAllowSortByAnyCol (bool sortByAnyCol)
Sets whether to allow sorting by any column, not only marked as sortable.
bool IsAllowSortByAnyCol ()
bool CanSortByHdrCell (wxAdvHdrCell *hdrCell)
Checks whether table can be sorted by specified header cell.
void SetHighlightMode (HighlightMode highlightMode)
Sets new highlight mode.
HighlightMode GetHighlightMode ()
Returns current highlight mode.
size_t GetRowCount ()
Returns row count.
size_t GetDecompRowCount ()
Returns decomposed row count.
size_t GetColCount ()
Returns column count.
size_t GetDecompColCount ()
Returns decomposed column count.
wxAdvHdrCell * GetRow (size_t index)
Returns row at specified index.
wxAdvHdrCell * GetDecompRow (size_t index)
Returns decomposed row at specified index.
wxAdvHdrCell * GetCol (size_t index)
Returns column at specified index.
wxAdvHdrCell * GetDecompCol (size_t index)
Returns decomposed column at specified index.
size_t MaxRow ()
Returns maximal row index.
size_t MaxCol ()
Returns maximal column index.
wxAdvTableDataModel * GetModel ()
Returns table data model.
wxAdvCellEditor * GetEditorForCell (size_t row, size_t col)
Returns editor to edit cell value.
void SetEditorForFormat (int format, wxAdvCellEditor *editor)
Set cell editor for specified cell format.
void StopEditing ()
Stop editing: deactivate editor if active, and commit changes.
wxAdvCellRenderer * GetRendererForCell (size_t row, size_t col)
Returns renderer for cell content.
void SetRendererForFormat (int format, wxAdvCellRenderer *renderer)
Sets table cell renderer for specified cell format.
void SetDefaultRenderer (wxAdvCellRenderer *renderer)
Sets default renderer to draw cell values.
void SetDefaultHdrRenderer (wxAdvHdrCellRenderer *renderer)
Sets default renderer to draw cell values.
wxString GetCellValue (size_t row, size_t col)
Returns table cell value.
void ChangeCellValue (size_t row, size_t col, wxString value)
Called by editor to change cell value.
bool IsCellEditable (size_t row, size_t col)
Checks whether cell is editable.
void ToModelCellCoord (size_t row, size_t col, size_t &modelRow, size_t &modelCol)
Transforms cell coordinate from table to model space.
void ToCellCoord (size_t row, size_t col, size_t &tableRow, size_t &tableCol)
Transforms cell coordinate from model to table space.
wxRect GetCellRect (size_t row, size_t col)
Returns table cell rectangle.
bool GetCellRect (wxRect &rc, size_t row, size_t col)
Returns table cell rectangle.
bool GetCellAt (const wxPoint &pt, size_t &row, size_t &col)
Returns cell coordinates at point.
wxAdvHdrCell * GetHdrCellAt (const wxPoint &pt)
Returns header cell (row or column) at given point.
bool IsCellSelected (size_t row, size_t col)
Checks if specified cell is selected.
bool IsCellHighlighted (size_t row, size_t col)
Checks if specified cell is highlighted.
void SetResizeAllRowsAllowed (bool resizeAllRowsAllowed)
Sets whether is allowed to resize all rows, not only marked by wxAdvHdrCell::Resizable.
bool IsResizeAllRowsAllowed ()
Checks whether is allowed to resize all rows, not only marked by wxAdvHdrCell::Resizable.
void SetResizeAllColsAllowed (bool resizeAllColsAllowed)
Sets whether is allowed to resize all columns, not only marked by wxAdvHdrCell::Resizable.
bool IsResizeAllColsAllowed ()
Checks whether is allowed to resize all columns, not only marked by wxAdvHdrCell::Resizable.
void SetSelection (wxAdvRange &range)
Sets selection range.
void SetSelection (size_t row, size_t col)
Sets selection to single cell in SelectCell mode, row - in SelectRows mode, column - in SelectCols mode.
void SetSelection (size_t row1, size_t col1, size_t row2, size_t col2)
Sets selection range.
bool GetVisibleRange (wxAdvRange &range)
Returns cells range currently visible.
const wxAdvRange & GetSelection ()
Returns selection range.
void ClearSelection ()
Clear selection.
void SetSelectMode (SelectMode selectMode)
Sets select mode.
int GetSelectMode ()
Returns current select mode.
bool IsCellFocused (size_t row, size_t col)
Checks if specified cell is in focus.
void SetFocusedCell (size_t row, size_t col)
Sets focused cell.
wxCoord CalcTotalColsWidth ()
Returns sum width of all columns.
wxCoord CalcTotalRowsHeight ()
Returns sum height of all rows.
wxCoord CalcTotalRowLayersWidth ()
Returns sum width of all rows layers.
wxCoord CalcTotalColLayersHeight ()
Returns sum height of all column layers.
void ScrollToCell (size_t row, size_t col)
Scrolls table to make specified cell visible.
wxRect CalcTableRect ()
Returns table area rectangle.
wxRect CalcRowsAreaRect ()
Returns rows area rectangle.
wxRect CalcColsAreaRect ()
Returns columns area rectangle.
wxRect CalcRowRect (size_t row, size_t col)
Calculate row rectangle.
wxRect CalcColRect (size_t row, size_t col)
Calculate column rectangle.
wxRect GetRangeRect (size_t row1, size_t col1, size_t row2, size_t col2)
Returns rectangle of cells range.
wxRect GetRangeRect (wxAdvRange &range)
Returns rectangle of cells range.
void SetBgBrush (const wxBrush &bgBrush)
Sets brush to draw cells background.
const wxBrush & GetBgBrush ()
Returns cells background brush.
void SetSelectedBgBrush (const wxBrush &selectedBgBrush)
Sets brush to draw selected cells background.
const wxBrush & GetSelectedBgBrush ()
Returns selected cells background brush.
void SetGridPen (const wxPen &gridPen)
Sets pen to draw grid lines.
const wxPen & GetGridPen ()
Returns grid lines pen.
void SetFocusedPen (const wxPen &focusedPen)
Sets pen to draw focused cell edges.
const wxPen & GetFocusedPen ()
Returns focused cell edges pen.
void SetFocusedBgBrush (const wxBrush &focusedBgBrush)
Sets brush to draw focused cells background.
const wxBrush & GetFocusedBgBrush ()
Returns focused cells background brush.
void SetHighlightedBgBrush (const wxBrush &highlightedBgBrush)
Sets brush to draw highlighted cells background.
const wxBrush & GetHighlightedBgBrush ()
Returns highlighted cells background brush.
virtual void ScrollWindow (int dx, int dy, const wxRect *rect)
wxWindow override To turn off physical scrolling, for smooth scroll.
virtual void SetFocus ()
wxPanel override.
virtual void CellChanged (size_t row, size_t col)
Called when single cell value has been changed.
virtual void TableChanged ()
Called when all table data has been changed.
Detailed Description
Main component class.
Advanced table control implementation.
Features:
composite rows/columns
sorting and filtering
MCV design (designed after Java(tm) JTable classes). Data accessed through wxAdvTableModel, rendered by wxAdvCellRenderer, edited by wxAdvCellEditor
rows/columns dynamic add/remove support
TODO: add printing support
TODO: add filters support
NOTES: There are two types of cell coordinates: table and model. Table coordinate used everywhere in table, when you click on cell, when you access data through wxAdvTable::GetCellValue. Model coordinates used by model.
Member Enumeration Documentation
enum wxAdvTable::HighlightMode
Enumerator:
HighlightNone
HighlightRows
HighlightCols
HighlightBoth
enum wxAdvTable::SelectMode
Enumerator:
SelectCell
SelectRows
SelectCols
SelectBlock
enum wxAdvTable::SortDirection
Enumerator:
SortDirAscending
SortDirDescending
SortDirNoSorting
enum wxAdvTable::SortMode
Enumerator:
SortRows
SortCols
SortDisabled
Constructor & Destructor Documentation
wxAdvTable::wxAdvTable (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
References NULL, wxBoolFormat, wxColourFormat, and wxStringFormat.
wxAdvTable::~wxAdvTable () [virtual]
Member Function Documentation
void wxAdvTable::AddCols (wxAdvHdrCell * cols, size_t numCols, size_t before = UNDEF_SIZE)
Add columns to table.
Parameters:
cols columns array
numCols number of columns in cols array
before index to column, before which to insert column, UNDEF_SIZE to insert at the end
References UpdateGeometry().
void wxAdvTable::AddRows (wxAdvHdrCell * rows, size_t numRows, size_t before = UNDEF_SIZE)
Add rows to table.
Parameters:
rows rows array
numRows number of rows in rows array
before index to row, before which to insert row, UNDEF_SIZE to insert at the end
References UpdateGeometry().
wxRect wxAdvTable::CalcColRect (size_t row, size_t col)
Calculate column rectangle.
Parameters:
row row index
col column index
Returns:
column rectangle
References CalcTableRect(), and GetCellRect().
wxRect wxAdvTable::CalcColsAreaRect ()
Returns columns area rectangle.
Returns:
columns area rectangle
References CalcTotalColsWidth().
wxRect wxAdvTable::CalcRowRect (size_t row, size_t col)
Calculate row rectangle.
Parameters:
row row index
col column index
Returns:
row rectangle
References CalcTableRect(), and GetCellRect().
wxRect wxAdvTable::CalcRowsAreaRect ()
Returns rows area rectangle.
Returns:
rows area rectangle
References CalcTotalColLayersHeight(), CalcTotalRowLayersWidth(), and CalcTotalRowsHeight().
wxRect wxAdvTable::CalcTableRect ()
Returns table area rectangle.
Returns:
table area rectangle
References CalcTotalColLayersHeight(), CalcTotalColsWidth(), CalcTotalRowLayersWidth(), and CalcTotalRowsHeight().
Referenced by CalcColRect(), CalcRowRect(), and GetVisibleRange().
wxCoord wxAdvTable::CalcTotalColLayersHeight () [inline]
Returns sum height of all column layers.
Returns:
sum height of all column layers
Referenced by CalcRowsAreaRect(), and CalcTableRect().
wxCoord wxAdvTable::CalcTotalColsWidth () [inline]
Returns sum width of all columns.
Returns:
sum width of all columns
Referenced by CalcColsAreaRect(), and CalcTableRect().
wxCoord wxAdvTable::CalcTotalRowLayersWidth () [inline]
Returns sum width of all rows layers.
Returns:
sum width of all rows layers
Referenced by CalcRowsAreaRect(), and CalcTableRect().
wxCoord wxAdvTable::CalcTotalRowsHeight () [inline]
Returns sum height of all rows.
Returns:
sum height of all rows
Referenced by CalcRowsAreaRect(), and CalcTableRect().
bool wxAdvTable::CanSortByHdrCell (wxAdvHdrCell * hdrCell)
Checks whether table can be sorted by specified header cell.
Parameters:
hdrCell header cell
Returns:
true if table can be sorted by specified header cell
References wxAdvHdrCell::IsComposite(), wxAdvHdrCell::IsSortable(), wxAdvHdrCell::m_isRow, SortCols, and SortRows.
void wxAdvTable::CellChanged (size_t row, size_t col) [virtual]
Called when single cell value has been changed.
Parameters:
row row index
col column index
Implements wxAdvTableDataModelObserver.
References GetCellRect(), and IsSorting().
void wxAdvTable::ChangeCellValue (size_t row, size_t col, wxString value)
Called by editor to change cell value.
row and column indices are in model coordinates.
Parameters:
row cell row index
col cell column index
value new cell value
References GetModel(), and wxAdvTableDataModel::SetCellValue().
Referenced by wxAdvCellEditor::SetNewValue().
void wxAdvTable::ClearSelection ()
Clear selection.
References wxAdvRange::Unset(), and wxAdvCoord::Unset().
Referenced by Create(), DestroyTable(), and SetSelectMode().
void wxAdvTable::Create (size_t numRows, size_t numCols, const wxString & cornerLabel, wxAdvTableDataModel * model)
Create table and arrange rows and columns, with specified row and column count.
Call this after you create wxAdvTable before using it. wxAdvTable takes ownership for table model
Parameters:
numRows number of elements in rows array
numCols number of elements in columns array
cornerLabel string to use as corner
model data model
References Create(), and NULL.
void wxAdvTable::Create (wxAdvHdrCell * rows, size_t numRows, size_t numCols, const wxString & cornerLabel, wxAdvTableDataModel * model)
Create table and arrange rows and columns, with specified column count.
Call this after you create wxAdvTable before using it. wxAdvTable takes ownership for table model
Parameters:
rows rows array
numRows number of elements in rows array
numCols number of elements in columns array
cornerLabel string to use as corner
model data model
References Create(), and NULL.
void wxAdvTable::Create (size_t numRows, wxAdvHdrCell * cols, size_t numCols, const wxString & cornerLabel, wxAdvTableDataModel * model)
Create table and arrange rows and columns, with specified row count.
Call this after you create wxAdvTable before using it. wxAdvTable takes ownership for table model
Parameters:
numRows number of elements in rows array
cols columns array
numCols number of elements in columns array
cornerLabel string to use as corner
model data model
References Create(), and NULL.
void wxAdvTable::Create (wxAdvHdrCellArray & rows, wxAdvHdrCellArray & cols, const wxString & cornerLabel, wxAdvTableDataModel * model)
Create table and arrange rows and columns.
Call this after you create wxAdvTable before using it. wxAdvTable takes ownership for table model
Parameters:
rows rows array
cols columns arrray
cornerLabel string to use as corner
model data model
References Create(), and FOREACH_HDRCELL.
void wxAdvTable::Create (wxAdvHdrCell * rows, size_t numRows, wxAdvHdrCell * cols, size_t numCols, const wxString & cornerLabel, wxAdvTableDataModel * model)
Create table and arrange rows and columns.
Call this after you create wxAdvTable before using it. wxAdvTable takes ownership for table model
Parameters:
rows rows array
numRows number of elements in rows array
cols columns arrray
numCols number of elements in columns array
cornerLabel string to use as corner
model data model
References Observable< O >::AddObserver(), ClearSelection(), DestroyTable(), wxAdvHdrCell::Label(), and UNDEF_SIZE.
Referenced by Create().
void wxAdvTable::DestroyTable ()
Destroy table, free data model.
References ClearSelection(), wxAdvHdrCell::Label(), wxAdvHdrCell::m_rc, NULL, and Observable< O >::RemoveObserver().
Referenced by Create().
const wxBrush & wxAdvTable::GetBgBrush ()
Returns cells background brush.
Returns:
cells background brush
bool wxAdvTable::GetCellAt (const wxPoint & pt, size_t & row, size_t & col)
Returns cell coordinates at point.
Parameters:
pt point
row output row index
col output column index
Returns:
true if point is in cell, false if point don't intersect any cell
References FOREACH_HDRCELL, and wxAdvHdrCell::m_rc.
bool wxAdvTable::GetCellRect (wxRect & rc, size_t row, size_t col)
Returns table cell rectangle.
Parameters:
rc reference to rectangle
row cell row index
col cell column index
Returns:
true if rc is set to table cell rectangle
wxRect wxAdvTable::GetCellRect (size_t row, size_t col)
Returns table cell rectangle.
Parameters:
row cell row index
col cell column index
Referenced by CalcColRect(), CalcRowRect(), CellChanged(), wxAdvCellEditor::GetCellRect(), and GetRangeRect().
wxString wxAdvTable::GetCellValue (size_t row, size_t col)
Returns table cell value.
Parameters:
row cell row index
col cell column index
References wxAdvTableDataModel::GetCellValue(), and ToModelCellCoord().
Referenced by wxAdvCellEditor::GetValue().
wxAdvHdrCell* wxAdvTable::GetCol (size_t index) [inline]
Returns column at specified index.
Parameters:
index column index
Returns:
column at specified index
References NULL.
Referenced by wxAdvHdrCell::RightSibling().
size_t wxAdvTable::GetColCount () [inline]
Returns column count.
Returns:
column count
wxAdvHdrCell* wxAdvTable::GetDecompCol (size_t index) [inline]
Returns decomposed column at specified index.
Parameters:
index decomposed column index
Returns:
decomposed column at specified index
Referenced by ScrollToCell().
size_t wxAdvTable::GetDecompColCount () [inline]
Returns decomposed column count.
Returns:
decomposed column count
wxAdvHdrCell* wxAdvTable::GetDecompRow (size_t index) [inline]
Returns decomposed row at specified index.
Parameters:
index decomposed row index
Returns:
decomposed row at specified index
Referenced by ScrollToCell().
size_t wxAdvTable::GetDecompRowCount () [inline]
Returns decomposed row count.
Returns:
decomposed row count
wxAdvCellEditor * wxAdvTable::GetEditorForCell (size_t row, size_t col)
Returns editor to edit cell value.
Parameters:
row cell row index
col cell column index
Returns:
editor for cell
References wxAdvTableDataModel::GetCellFormat(), NULL, and ToModelCellCoord().
const wxBrush & wxAdvTable::GetFocusedBgBrush ()
Returns focused cells background brush.
Returns:
focused cells background brush
const wxPen & wxAdvTable::GetFocusedPen ()
Returns focused cell edges pen.
Returns:
focused cell edges pen
const wxPen & wxAdvTable::GetGridPen ()
Returns grid lines pen.
Returns:
grid lines pen
wxAdvHdrCell * wxAdvTable::GetHdrCellAt (const wxPoint & pt)
Returns header cell (row or column) at given point.
Returns:
header cell or NULL if not found
References FOREACH_HDRCELL, and NULL.
const wxBrush & wxAdvTable::GetHighlightedBgBrush ()
Returns highlighted cells background brush.
Returns:
highlighted cells background brush
HighlightMode wxAdvTable::GetHighlightMode () [inline]
Returns current highlight mode.
Returns:
current highlight mode
wxAdvTableDataModel* wxAdvTable::GetModel () [inline]
Returns table data model.
Returns:
table data model
Referenced by ChangeCellValue(), wxAdvTableDateTimeSorter::Compare(), wxAdvTableDoubleSorter::Compare(), and wxAdvTableStringSorter::Compare().
wxRect wxAdvTable::GetRangeRect (wxAdvRange & range)
Returns rectangle of cells range.
Parameters:
range cells range
Returns:
rectangle of cells range
References wxAdvRange::Col1(), wxAdvRange::Col2(), GetRangeRect(), wxAdvRange::Row1(), and wxAdvRange::Row2().
wxRect wxAdvTable::GetRangeRect (size_t row1, size_t col1, size_t row2, size_t col2)
Returns rectangle of cells range.
Parameters:
row1 first row index
col1 first column index
row2 second row index
col2 second column index
Returns:
rectangle of cells range
References GetCellRect().
Referenced by GetRangeRect().
wxAdvCellRenderer * wxAdvTable::GetRendererForCell (size_t row, size_t col)
Returns renderer for cell content.
Parameters:
row cell row index
col cell column index
Returns:
renderer for cell content
References wxAdvTableDataModel::GetCellFormat(), and ToModelCellCoord().
wxAdvHdrCell* wxAdvTable::GetRow (size_t index) [inline]
Returns row at specified index.
Parameters:
index row index
Returns:
row at specified index
References NULL.
Referenced by wxAdvHdrCell::RightSibling().
size_t wxAdvTable::GetRowCount () [inline]
Returns row count.
Returns:
row count
const wxBrush & wxAdvTable::GetSelectedBgBrush ()
Returns selected cells background brush.
Returns:
selected cells background brush
const wxAdvRange& wxAdvTable::GetSelection ()
Returns selection range.
Returns:
selection range
int wxAdvTable::GetSelectMode ()
Returns current select mode.
Returns:
select mode
bool wxAdvTable::GetShowCols () [inline]
Returns true, if columns header is shown.
Returns:
true, if columns header is shown.
bool wxAdvTable::GetShowCorner () [inline]
Returns true, if table corner is shown.
Returns:
true, if table corner is shown.
bool wxAdvTable::GetShowRows () [inline]
Returns true, if rows header is shown.
Returns:
true, if rows header is shown.
wxAdvTable::SortDirection wxAdvTable::GetSortDirection ()
Returns current sort direction.
Returns:
current sort direction
wxAdvTableSorter * wxAdvTable::GetSorter ()
Returns sorter to sort table data.
Returns:
sorter to sort table data
size_t wxAdvTable::GetSortingIndex ()
Returns current row/column index for sorting.
Returns:
current row/column index for sorting
wxAdvTable::SortMode wxAdvTable::GetSortMode ()
Returns current sort mode.
Returns:
current sort mode
bool wxAdvTable::GetVisibleRange (wxAdvRange & range)
Returns cells range currently visible.
Parameters:
range output visible range
Returns:
true if range filled is visible range, false - if nothing is visible
References CalcTableRect(), wxAdvHdrCell::m_rc, wxAdvRange::Set(), and UNDEF_SIZE.
Referenced by ScrollToCell().
bool wxAdvTable::IsAllowSortByAnyCol ()
bool wxAdvTable::IsAllowSortByAnyRow ()
bool wxAdvTable::IsCellEditable (size_t row, size_t col)
Checks whether cell is editable.
Parameters:
row cell row index
col cell column index
Returns:
true if cell is editable, false - overwise
References wxAdvTableDataModel::IsCellEditable(), and ToModelCellCoord().
bool wxAdvTable::IsCellFocused (size_t row, size_t col) [inline]
Checks if specified cell is in focus.
Parameters:
row row index of cell
col column index of cell
bool wxAdvTable::IsCellHighlighted (size_t row, size_t col)
Checks if specified cell is highlighted.
Parameters:
row cell row index
col cell column index
References wxAdvCoord::Col(), HighlightBoth, HighlightCols, HighlightNone, HighlightRows, and wxAdvCoord::Row().
bool wxAdvTable::IsCellSelected (size_t row, size_t col) [inline]
Checks if specified cell is selected.
Parameters:
row cell row index
col cell column index
bool wxAdvTable::IsResizeAllColsAllowed () [inline]
Checks whether is allowed to resize all columns, not only marked by wxAdvHdrCell::Resizable.
Returns:
true if all columns are resizable
bool wxAdvTable::IsResizeAllRowsAllowed () [inline]
Checks whether is allowed to resize all rows, not only marked by wxAdvHdrCell::Resizable.
Returns:
true if all rows are resizable
bool wxAdvTable::IsSorting ()
Checks whether table is sorted.
Returns:
true if table is sorted
References MaxCol(), MaxRow(), NULL, SortCols, and SortRows.
Referenced by CellChanged(), TableChanged(), ToCellCoord(), and ToModelCellCoord().
size_t wxAdvTable::MaxCol () [inline]
Returns maximal column index.
Returns:
maximal column index
Referenced by IsSorting(), ScrollToCell(), and SetFocusedCell().
size_t wxAdvTable::MaxRow () [inline]
Returns maximal row index.
Returns:
maximal row index
Referenced by IsSorting(), ScrollToCell(), and SetFocusedCell().
void wxAdvTable::RemoveCols (size_t from, size_t count)
Remove columns from table.
Parameters:
from first index to remove
count columns count to remove
References RemoveHdrCells().
void wxAdvTable::RemoveHdrCell (wxAdvHdrCell * hdrCell)
Remove header cell from table.
Parameters:
hdrCell header cell to remove
References wxAdvHdrCell::m_isRow, wxAdvHdrCell::m_parent, wxAdvHdrCell::m_subIndex, NULL, RemoveHdrCells(), wxAdvHdrCell::RemoveSubCell(), and UpdateGeometry().
void wxAdvTable::RemoveHdrCells (size_t from, size_t count, bool isRows)
Remove header cells from table.
Parameters:
from first index to remove
count cells count to remove
isRows true if you want to remove rows, false - columns
References NULL, and UpdateGeometry().
Referenced by RemoveCols(), RemoveHdrCell(), and RemoveRows().
void wxAdvTable::RemoveRows (size_t from, size_t count)
Remove rows from table.
Parameters:
from first index to remove
count rows count to remove
References RemoveHdrCells().
void wxAdvTable::ScrollToCell (size_t row, size_t col)
Scrolls table to make specified cell visible.
Parameters:
row row index
col column index
References wxAdvRange::BottomRow(), GetDecompCol(), GetDecompRow(), GetVisibleRange(), wxAdvRange::LeftCol(), wxAdvHdrCell::m_rc, MaxCol(), MaxRow(), wxAdvRange::RightCol(), and wxAdvRange::TopRow().
virtual void wxAdvTable::ScrollWindow (int dx, int dy, const wxRect * rect) [virtual]
wxWindow override To turn off physical scrolling, for smooth scroll.
void wxAdvTable::SetAllowSortByAnyCol (bool sortByAnyCol)
Sets whether to allow sorting by any column, not only marked as sortable.
Parameters:
sortByAnyCol true if you want to sort by any column
void wxAdvTable::SetAllowSortByAnyRow (bool sortByAnyRow)
Sets whether to allow sorting by any row, not only marked as sortable.
Parameters:
sortByAnyRow true if you want to sort by any row
void wxAdvTable::SetBgBrush (const wxBrush & bgBrush)
Sets brush to draw cells background.
Parameters:
bgBrush new brush
void wxAdvTable::SetDefaultHdrRenderer (wxAdvHdrCellRenderer * renderer)
Sets default renderer to draw cell values.
wxAdvTable takes ownership over renderer.
Parameters:
renderer new default renderer
void wxAdvTable::SetDefaultRenderer (wxAdvCellRenderer * renderer)
Sets default renderer to draw cell values.
wxAdvTable takes ownership over renderer.
Parameters:
renderer new default renderer
References wxREPLACE.
void wxAdvTable::SetEditorForFormat (int format, wxAdvCellEditor * editor)
Set cell editor for specified cell format.
wxAdvTable takes ownership over editor.
Parameters:
format cell format
editor cell editor for format
void wxAdvTable::SetFocus () [virtual]
wxPanel override.
This is focus change bugfix.
Referenced by StopEditing().
void wxAdvTable::SetFocusedBgBrush (const wxBrush & focusedBgBrush)
Sets brush to draw focused cells background.
Parameters:
focusedBgBrush new brush
References wxAdvCoord::Col(), wxAdvCoord::IsSet(), and wxAdvCoord::Row().
void wxAdvTable::SetFocusedCell (size_t row, size_t col)
Sets focused cell.
Parameters:
row cell row index
col cell column index
References wxAdvCoord::Equal(), MaxCol(), MaxRow(), wxAdvCoord::Set(), and StopEditing().
void wxAdvTable::SetFocusedPen (const wxPen & focusedPen)
Sets pen to draw focused cell edges.
Parameters:
focusedPen new grid pen
References wxAdvCoord::Col(), wxAdvCoord::IsSet(), and wxAdvCoord::Row().
void wxAdvTable::SetGridPen (const wxPen & gridPen)
Sets pen to draw grid lines.
Parameters:
gridPen new grid pen
void wxAdvTable::SetHighlightedBgBrush (const wxBrush & highlightedBgBrush)
Sets brush to draw highlighted cells background.
Parameters:
highlightedBgBrush new brush
void wxAdvTable::SetHighlightMode (HighlightMode highlightMode)
Sets new highlight mode.
Parameters:
highlightMode new highlight mode
void wxAdvTable::SetRendererForFormat (int format, wxAdvCellRenderer * renderer)
Sets table cell renderer for specified cell format.
wxAdvTable takes ownership over renderer.
Parameters:
format cell format
renderer renderer for cell format
void wxAdvTable::SetResizeAllColsAllowed (bool resizeAllColsAllowed) [inline]
Sets whether is allowed to resize all columns, not only marked by wxAdvHdrCell::Resizable.
Parameters:
resizeAllColsAllowed true to make all columns resizable
void wxAdvTable::SetResizeAllRowsAllowed (bool resizeAllRowsAllowed) [inline]
Sets whether is allowed to resize all rows, not only marked by wxAdvHdrCell::Resizable.
Parameters:
resizeAllRowsAllowed true to make all rows resizable
void wxAdvTable::SetSelectedBgBrush (const wxBrush & selectedBgBrush)
Sets brush to draw selected cells background.
Parameters:
selectedBgBrush new brush
void wxAdvTable::SetSelection (size_t row1, size_t col1, size_t row2, size_t col2)
Sets selection range.
Parameters:
row1 first row index
col1 first column index
row2 second row index
col2 second column index
References wxAdvRange::Set().
void wxAdvTable::SetSelection (size_t row, size_t col)
Sets selection to single cell in SelectCell mode, row - in SelectRows mode, column - in SelectCols mode.
Parameters:
row cell row index
col cell column index
References SetSelection().
void wxAdvTable::SetSelection (wxAdvRange & range)
Sets selection range.
Parameters:
range new selected range
References wxAdvRange::Col1(), wxAdvRange::Col2(), wxAdvRange::Row1(), and wxAdvRange::Row2().
Referenced by SetSelection().
void wxAdvTable::SetSelectMode (SelectMode selectMode)
Sets select mode.
Parameters:
selectMode new select mode, possible values: SelectCell, SelectRows, SelectCols, SelectBlock.
References ClearSelection().
void wxAdvTable::SetShowCols (bool showCols) [inline]
Sets whether to show columns header.
Parameters:
showCols true if you wish to columns header to be shown
void wxAdvTable::SetShowCorner (bool showCorner) [inline]
Sets whether to show table corner.
Parameters:
showCorner true if you wish to corner to be shown
void wxAdvTable::SetShowHeaders (bool showRows, bool showCols, bool showCorner)
Sets headers (row, column, corner header) show params.
Parameters:
showRows true if you wish to rows header to be shown
showCols true if you wish to cols header to be shown
showCorner true if you wish to corner header to be shown
void wxAdvTable::SetShowRows (bool showRows) [inline]
Sets whether to show rows header.
Parameters:
showRows true if you wish to rows header to be shown
void wxAdvTable::SetSortDirection (SortDirection sortDirection)
Sets sort direction.
Parameters:
sortDirection sort direction;
void wxAdvTable::SetSorter (wxAdvTableSorter * sorter)
Sets sorter to sort table data.
wxAdvTable takes ownership for sorter object.
Parameters:
sorter new sorter
References wxREPLACE.
void wxAdvTable::SetSortingIndex (size_t sortingIndex, bool invert = true)
Sets row/column index for sorting.
Parameters:
sortingIndex index for sorting
invert if true and sortingIndex is same as before call, sorting direction will be inverted
References SortDirAscending, SortDirDescending, SortDirNoSorting, and UNDEF_SIZE.
void wxAdvTable::SetSortMode (SortMode sortMode)
Sets sorting mode (eg Rows to sort rows - vertical sort, or Cols to sort columns - horizontal sort).
Parameters:
sortMode new sorting mode
References UNDEF_SIZE.
void wxAdvTable::StopEditing ()
Stop editing: deactivate editor if active, and commit changes.
References wxAdvCellEditor::Deactivate(), NULL, SetFocus(), and UNDEF_SIZE.
Referenced by wxAdvCellEditor::EndEditing(), and SetFocusedCell().
void wxAdvTable::TableChanged () [virtual]
Called when all table data has been changed.
Implements wxAdvTableDataModelObserver.
References IsSorting().
void wxAdvTable::ToCellCoord (size_t row, size_t col, size_t & tableRow, size_t & tableCol)
Transforms cell coordinate from model to table space.
Parameters:
row model row index
col model column index
tableRow output table row index
tableCol output table column index
References IsSorting(), SortCols, and SortRows.
void wxAdvTable::ToModelCellCoord (size_t row, size_t col, size_t & modelRow, size_t & modelCol)
Transforms cell coordinate from table to model space.
Parameters:
row table row index
col table column index
modelRow output model row index
modelCol output model column index
References IsSorting(), SortCols, and SortRows.
Referenced by GetCellValue(), GetEditorForCell(), GetRendererForCell(), IsCellEditable(), and wxAdvCellEditor::SetNewValue().
void wxAdvTable::UpdateGeometry ()
Recalculate entire table geometry and repaint it.
Need to be called by user after change in hdrCell attributes.
Referenced by AddCols(), AddRows(), RemoveHdrCell(), and RemoveHdrCells().
The documentation for this class was generated from the following files:
wxadvtable.h
wxadvtable.cpp