wxAdvTable: wxAdvTableDoubleSorter Class Reference
wxAdvTableDoubleSorter Class Reference
Sorts data by comparing double values.
#include <wxadvtable.h>
Public Member Functions
wxAdvTableDoubleSorter ()
virtual ~wxAdvTableDoubleSorter ()
virtual int Compare (wxAdvTable *table, size_t row1, size_t col1, size_t row2, size_t col2)
Detailed Description
Sorts data by comparing double values.
Constructor & Destructor Documentation
wxAdvTableDoubleSorter::wxAdvTableDoubleSorter ()
wxAdvTableDoubleSorter::~wxAdvTableDoubleSorter () [virtual]
Member Function Documentation
int wxAdvTableDoubleSorter::Compare (wxAdvTable * table, size_t row1, size_t col1, size_t row2, size_t col2) [virtual]
Reimplemented from wxAdvTableStringSorter.
References wxAdvTableDataModel::GetCellFormat(), wxAdvTableDataModel::GetCellValueAsDouble(), wxAdvTable::GetModel(), and wxDoubleFormat.
The documentation for this class was generated from the following files:
wxadvtable.h
wxadvtable.cpp