#ifndef __WXLIBIRCLIENTDEFS_H__
#define __WXLIBIRCLIENTDEFS_H__

#ifdef USING_SOURCE_LIBIRCLIENT
	#define WXDLLIMPEXP_LIBIRCLIENT
    #define WXDLLIMPEXP_DATA_LIBIRCLIENT(type) type
#elif defined( LIB_USINGDLL )
    #define WXDLLIMPEXP_LIBIRCLIENT
    #define WXDLLIMPEXP_DATA_LIBIRCLIENT(type)
#elif defined( WXMAKINGDLL_LIBIRCLIENT )
    #define WXDLLIMPEXP_LIBIRCLIENT WXEXPORT
    #define WXDLLIMPEXP_DATA_LIBIRCLIENT(type) WXEXPORT type
#elif defined(WXUSINGDLL)
    #define WXDLLIMPEXP_LIBIRCLIENT WXIMPORT
    #define WXDLLIMPEXP_DATA_LIBIRCLIENT(type) WXIMPORT type
#else // not making nor using DLL
    #define WXDLLIMPEXP_LIBIRCLIENT
    #define WXDLLIMPEXP_DATA_LIBIRCLIENT(type) type
#endif

#endif //__WXLIBIRCLIENTDEFS_H__
