#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows sample (Cygwin/Mingw32).

WXDIR = $(WXWIN)

TARGET=panoViewer
OBJECTS = PanoViewExtractor.o PanoImage.o panolib.o printError.o $(TARGET).o 

include $(WXDIR)\src\makeprog.g95

