//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: wxvidcap.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_wxvidcap_H__
#define __WDR_wxvidcap_H__

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

wxBitmap ToolBarBitmaps( size_t index );

#endif

// End of generated file
