########################
# Makefile for Archive
########################

# Adjust this to match the archive dir

LIBNAME  = ../lib/libtreemultictrl

# Adjust the include directories to match
# your library include path

INCLUDE += -I./ \
           -I../include

# Add the sources you need for your library

SOURCES = \
		TreeMultiItemBase.cpp \
		TreeMultiItemRoot.cpp \
		TreeMultiItemNode.cpp \
		TreeMultiItemWindow.cpp \
		wxTreeMultiCtrl.cpp

include ../Makefile.Envs

build: $(ARCHIVE)


